#include "strut/api_registry.h"

#include <algorithm>
#include <cctype>

namespace strut { namespace {
TypeId t(std::string_view value){return intern_type(value);}
ApiOverload overload(std::initializer_list<std::pair<const char*,const char*>> parameters,const char* result){ApiOverload o;for(const auto& p:parameters)o.parameters.push_back({p.first,t(p.second),false});o.return_type=t(result);return o;}
ApiOverload optional_last(ApiOverload value){if(!value.parameters.empty())value.parameters.back().optional=true;return value;}
ApiCallable call(const char* name,const char* category,const char* module,const char* owner,ApiOverload signature,std::initializer_list<const char*> errors,std::initializer_list<RuntimeComponentId> runtime,const char* summary){ApiCallable c;c.name=name;c.category=category;c.module=module;c.owner=owner;c.overloads.push_back(std::move(signature));c.runtime_components=runtime;c.summary=summary;for(auto e:errors)c.checked_errors.emplace_back(e);return c;}
ApiCallable with_overload(ApiCallable value,ApiOverload signature){value.overloads.push_back(std::move(signature));return value;}
ApiCallable generic_call(const char* name,const char* module,ApiOverload signature,RuntimeComponentId runtime,const char* summary){auto c=call(name,"function",module,"",std::move(signature),{},{runtime},summary);c.generic_parameters={"T"};return c;}
std::string lower(std::string_view value){std::string out(value);std::transform(out.begin(),out.end(),out.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return out;}
}

const std::vector<ApiCallable>& api_callables(){
    using R=RuntimeComponentId;
    static const std::vector<ApiCallable> items={
        generic_call("print","core",overload({{"value","T"}},"void"),R::core,"Write a value without a trailing newline."),
        generic_call("println","core",overload({{"value","T"}},"void"),R::core,"Write a value followed by a newline."),
        with_overload(call("bytes","constructor","core","",overload({},"bytes"),{},{R::bytes},"Create an owned byte value."),overload({{"size","int_64"}},"bytes")),
        call("input","function","core","",overload({},"string"),{},{R::io},"Read a line from standard input."),
        call("base64_encode","function","encoding","",overload({{"data","bytes"}},"string"),{},{R::encoding},"Encode bytes using canonical padded RFC 4648 Base64."),
        call("base64_decode","function","encoding","",overload({{"text","string"}},"bytes"),{"EncodingError"},{R::encoding},"Decode strict canonical padded RFC 4648 Base64."),
        call("base64url_encode","function","encoding","",overload({{"data","bytes"}},"string"),{},{R::encoding},"Encode bytes using canonical unpadded RFC 4648 Base64url."),
        call("base64url_decode","function","encoding","",overload({{"text","string"}},"bytes"),{"EncodingError"},{R::encoding},"Decode strict canonical unpadded RFC 4648 Base64url."),
        call("secure_random_bytes","function","crypto","",overload({{"count","int_64"}},"bytes"),{"CryptoError"},{R::crypto},"Generate bytes using the platform cryptographic random source."),
        call("sha256","function","crypto","",overload({{"data","bytes"}},"bytes"),{"CryptoError"},{R::crypto},"Compute a raw 32-byte SHA-256 digest."),
        call("hmac_sha256","function","crypto","",overload({{"key","bytes"},{"data","bytes"}},"bytes"),{"CryptoError"},{R::crypto},"Compute a raw 32-byte HMAC-SHA-256 authenticator."),
        call("constant_time_equal","function","crypto","",overload({{"left","bytes"},{"right","bytes"}},"bool"),{},{R::crypto},"Compare equal-length byte values without content-dependent early exit."),
        generic_call("new","memory",overload({{"value","T"}},"ptr<T>"),R::safe_pointer,"Create a reference-counted safe pointer."),
        generic_call("weak","memory",overload({{"owner","ptr<T>"}},"weak_ptr<T>"),R::weak_pointer,"Create a weak pointer."),
        generic_call("ptr","memory",overload({{"owner","ptr<T>"}},"raw_ptr<T>"),R::raw_pointer,"Create a non-owning raw pointer in an unsafe block."),
        generic_call("ref","memory",overload({{"value","T"}},"ref<T>"),R::safe_pointer,"Borrow an lvalue by reference."),
        call("http_get","function","http","",overload({{"url","string"}},"http_response"),{"HttpError"},{R::http_client},"Perform a bounded buffered HTTP GET request."),
        call("http_get_ca","function","http","",overload({{"url","string"},{"ca_file","string"}},"http_response"),{"HttpError"},{R::http_client},"Perform a verified HTTPS GET using an explicit PEM CA bundle."),
        call("http_request","function","http","",optional_last(overload({{"method","string"},{"url","string"},{"options","json"}},"http_response")),{"HttpError"},{R::http_client},"Perform a configurable bounded buffered HTTP request."),
        call("http_get_json","function","http","",overload({{"url","string"}},"json"),{"HttpError"},{R::http_client},"Fetch and parse a JSON response."),
        call("http_get_async","function","http","",overload({{"url","string"}},"future<http_response>"),{"HttpError"},{R::http_client,R::async},"Start an asynchronous HTTP GET request."),
        call("http_request_async","function","http","",overload({{"method","string"},{"url","string"},{"options","json"}},"future<http_response>"),{"HttpError"},{R::http_client,R::async},"Start an asynchronous HTTP request."),
        with_overload(call("http_request_stream","function","http","",overload({{"method","string"},{"url","string"},{"options","json"},{"upload","function<(int_64)->bytes>?"},{"download","function<(bytes)->bool>?"}},"http_response_head"),{"HttpError"},{R::http_client_streaming},"Stream an HTTP upload and/or download with bounded binary chunks."),overload({{"method","string"},{"url","string"},{"options","json"},{"upload","function<(int_64)->bytes>?"},{"download","function<(bytes)->bool>?"},{"cancellation","cancellation_token"}},"http_response_head")),
        with_overload(call("http_request_stream_async","function","http","",overload({{"method","string"},{"url","string"},{"options","json"},{"upload","function<(int_64)->bytes>?"},{"download","function<(bytes)->bool>?"}},"future<http_response_head>"),{"HttpError"},{R::http_client_streaming,R::async},"Start a bounded streaming HTTP transfer on the shared executor."),overload({{"method","string"},{"url","string"},{"options","json"},{"upload","function<(int_64)->bytes>?"},{"download","function<(bytes)->bool>?"},{"cancellation","cancellation_token"}},"future<http_response_head>")),
        call("http_server","function","http","",overload({},"http_server"),{},{R::http_server},"Create a plain HTTP server."),
        call("http_text","function","http","",overload({{"body","string"}},"http_server_response"),{},{R::http_server},"Create a text response."),
        call("http_html","function","http","",overload({{"body","string"}},"http_server_response"),{},{R::http_server},"Create an HTML response."),
        call("http_json_response","function","http","",overload({{"body","json"}},"http_server_response"),{},{R::http_server,R::json},"Create a JSON response."),
        call("http_cookie","function","http","",overload({{"name","string"},{"value","string"}},"http_cookie"),{},{R::http_server},"Create a structured response cookie whose attributes can be configured before emission."),
        call("http_redirect","function","http","",optional_last(overload({{"location","string"},{"status","int"}},"http_server_response")),{"HttpError"},{R::http_server},"Create an empty 301, 302, 303, 307, or 308 redirect response."),
        call("http_serve_file","function","http","",optional_last(overload({{"request","http_request"},{"writer","http_response_writer"},{"path","string"},{"content_type","string"}},"void")),{"FilesystemError","NetworkError"},{R::http_file_response},"Stream an explicit filesystem path with single-byte-range support."),
        call("http_write_ndjson","function","http","",overload({{"request","http_request"},{"writer","http_response_writer"},{"value","json"}},"void"),{"HttpError","NetworkError"},{R::http_ndjson},"Validate, write, and flush one cancellation-aware NDJSON record."),
        call("tls_connect","function","networking","",overload({{"host","string"},{"port","int"}},"tls_stream"),{"TlsError"},{R::http_client},"Open a verified client TLS stream."),
        call("tcp_connect","function","networking","",overload({{"host","string"},{"port","int"}},"tcp_socket"),{"NetworkError"},{R::networking},"Open a TCP connection."),
        call("tcp_connect_async","function","networking","",overload({{"host","string"},{"port","int"}},"future<tcp_socket>"),{"NetworkError"},{R::networking,R::async},"Open a TCP connection asynchronously."),
        call("tcp_listen","function","networking","",optional_last(overload({{"host","string"},{"port","int"},{"backlog","int"}},"tcp_listener")),{"NetworkError"},{R::networking},"Create a TCP listener."),
        call("sqlite_open","function","sqlite","",overload({{"path","string"}},"sqlite_db"),{"SqliteError"},{R::sqlite},"Open a SQLite database."),
        call("exec","function","process","",optional_last(overload({{"program","string"},{"args","string[]"},{"options","json"}},"exec_result")),{"ExecError"},{R::process},"Execute a program without shell interpolation."),
        call("exec_shell","function","process","",overload({{"command","string"}},"exec_result"),{"ExecError"},{R::process},"Execute an explicit shell command."),
        with_overload(with_overload(with_overload(call("process","function","process","",overload({{"program","string"},{"args","string[]"}},"process"),{"ExecError"},{R::process},"Start a streaming process in an owned POSIX process group or Windows Job, with optional cwd/environment and cancellable pipe operations."),overload({{"program","string"},{"args","string[]"},{"options","json"}},"process")),overload({{"program","string"},{"args","string[]"},{"token","cancellation_token"}},"process")),overload({{"program","string"},{"args","string[]"},{"options","json"},{"token","cancellation_token"}},"process")),
        with_overload(with_overload(with_overload(call("pty_spawn","function","pty","",overload({{"program","string"},{"args","string[]"}},"pty"),{"PtyError"},{R::pty},"Start an arbitrary executable on a binary pseudo-terminal with optional cwd, environment, initial size, and cancellable I/O."),overload({{"program","string"},{"args","string[]"},{"options","json"}},"pty")),overload({{"program","string"},{"args","string[]"},{"token","cancellation_token"}},"pty")),overload({{"program","string"},{"args","string[]"},{"options","json"},{"token","cancellation_token"}},"pty")),
        call("pipe_exec","function","process","",overload({{"first","string"},{"first_args","string[]"},{"second","string"},{"second_args","string[]"}},"exec_result"),{"ExecError"},{R::process},"Execute a two-stage argv pipeline while concurrently draining stdout and both stderr streams."),
        call("embed_file","function","embedding","",overload({{"path","string"}},"string"),{"EmbedError"},{R::embedded_assets},"Embed a file at compile time."),
        call("embed_dir","function","embedding","",overload({{"path","string"}},"map<string,string>"),{"EmbedError"},{R::embedded_assets},"Embed a directory at compile time."),
        call("env","function","system","",overload({{"name","string"}},"string?"),{},{R::environment},"Read an environment variable."),
        call("set_env","function","system","",overload({{"name","string"},{"value","string"}},"void"),{"EnvironmentError"},{R::environment},"Set an environment variable."),
        call("unset_env","function","system","",overload({{"name","string"}},"void"),{"EnvironmentError"},{R::environment},"Remove an environment variable."),
        call("sleep_ms","function","time","",overload({{"milliseconds","int_64"}},"void"),{"TimeError"},{R::time},"Sleep for a non-negative duration."),
        call("now_ms","function","time","",overload({},"int_64"),{},{R::time},"Read a monotonic millisecond clock."),
        call("unix_ms","function","time","",overload({},"int_64"),{},{R::time},"Read Unix time in milliseconds."),
        call("wait_for_shutdown_signal","function","system","",overload({},"void"),{},{R::time},"Wait safely for SIGINT or SIGTERM outside the raw signal-handler context."),
        call("exists","function","filesystem","",overload({{"path","string"}},"bool"),{"FilesystemError"},{R::filesystem},"Test whether a path exists."),
        call("is_file","function","filesystem","",overload({{"path","string"}},"bool"),{"FilesystemError"},{R::filesystem},"Test whether a path is a file."),
        call("is_dir","function","filesystem","",overload({{"path","string"}},"bool"),{"FilesystemError"},{R::filesystem},"Test whether a path is a directory."),
        call("file_size","function","filesystem","",overload({{"path","string"}},"int_64"),{"FilesystemError"},{R::filesystem},"Read a file size."),
        call("modified","function","filesystem","",overload({{"path","string"}},"int_64"),{"FilesystemError"},{R::filesystem},"Read a path modification time."),
        call("make_dir","function","filesystem","",overload({{"path","string"}},"void"),{"FilesystemError"},{R::filesystem},"Create a directory."),
        call("remove","function","filesystem","",overload({{"paths","string"}},"void"),{"FilesystemError"},{R::filesystem},"Remove one or more paths."),
        call("remove_all","function","filesystem","",overload({{"path","string"}},"void"),{"FilesystemError"},{R::filesystem},"Remove a path recursively."),
        call("copy","function","filesystem","",overload({{"source","string"},{"destination","string"}},"void"),{"FilesystemError"},{R::filesystem},"Copy paths, including ordered pairwise collections."),
        call("move","function","filesystem","",overload({{"source","string"},{"destination","string"}},"void"),{"FilesystemError"},{R::filesystem},"Move paths, including ordered pairwise collections."),
        call("touch","function","filesystem","",overload({{"path","string"}},"void"),{"FilesystemError"},{R::filesystem},"Create a file or update its timestamp."),
        call("read_file","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Read a complete UTF-8 file."),
        call("read_bytes","function","filesystem","",overload({{"path","string"}},"bytes"),{"FilesystemError"},{R::filesystem},"Read a complete binary file."),
        with_overload(call("write_file","function","filesystem","",overload({{"path","string"},{"data","string"}},"void"),{"FilesystemError"},{R::filesystem},"Write a complete file."),overload({{"path","string"},{"data","bytes"}},"void")),
        with_overload(call("append_file","function","filesystem","",overload({{"path","string"},{"data","string"}},"void"),{"FilesystemError"},{R::filesystem},"Append to a file."),overload({{"path","string"},{"data","bytes"}},"void")),
        call("ls","function","filesystem","",overload({{"path","string"}},"string[]"),{"FilesystemError"},{R::filesystem},"List a directory."),
        call("walk","function","filesystem","",overload({{"path","string"}},"string[]"),{"FilesystemError"},{R::filesystem},"Walk a directory recursively."),
        call("cwd","function","filesystem","",overload({},"string"),{"FilesystemError"},{R::filesystem},"Read the current working directory."),
        call("cd","function","filesystem","",overload({{"path","string"}},"void"),{"FilesystemError"},{R::filesystem},"Change the current working directory."),
        call("absolute","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Create an absolute path."),
        call("canonical","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Canonicalize a path."),
        call("parent","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Read the parent path."),
        call("filename","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Read the final path component."),
        call("extension","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Read a file extension."),
        call("stem","function","filesystem","",overload({{"path","string"}},"string"),{"FilesystemError"},{R::filesystem},"Read a file stem."),
        call("join_path","function","filesystem","",overload({{"left","string"},{"right","string"}},"string"),{"FilesystemError"},{R::filesystem},"Join path components."),
        call("atomic<T>.load","method","concurrency","atomic<T>",overload({},"T"),{},{R::atomics},"Load the value with sequentially consistent ordering."),
        call("atomic<T>.store","method","concurrency","atomic<T>",overload({{"value","T"}},"void"),{},{R::atomics},"Store a value with sequentially consistent ordering."),
        call("atomic<T>.exchange","method","concurrency","atomic<T>",overload({{"value","T"}},"T"),{},{R::atomics},"Replace and return the previous value."),
        call("atomic<T>.compare_exchange","method","concurrency","atomic<T>",overload({{"expected","T"},{"desired","T"}},"bool"),{},{R::atomics},"Replace the expected value atomically."),
        call("atomic<T>.fetch_add","method","concurrency","atomic<T>",overload({{"value","T"}},"T"),{},{R::atomics},"Add and return the previous integer value."),
        call("atomic<T>.fetch_sub","method","concurrency","atomic<T>",overload({{"value","T"}},"T"),{},{R::atomics},"Subtract and return the previous integer value."),
        call("future<T>.get","method","concurrency","future<T>",overload({},"T"),{},{R::async},"Wait for and return the asynchronous result."),
        call("future<T>.valid","method","concurrency","future<T>",overload({},"bool"),{},{R::async},"Report whether the future contains shared state."),
        call("channel<T>.send","method","concurrency","channel<T>",overload({{"value","T"}},"void"),{},{R::channels},"Send a value to the channel."),
        call("channel<T>.receive","method","concurrency","channel<T>",overload({},"T?"),{},{R::channels},"Wait for and receive a value, or null after close."),
        call("channel<T>.close","method","concurrency","channel<T>",overload({},"void"),{},{R::channels},"Close the channel."),
        call("channel<T>.closed","method","concurrency","channel<T>",overload({},"bool"),{},{R::channels},"Report whether the channel is closed."),
        with_overload(call("mutex.lock","method","concurrency","mutex",overload({},"void"),{},{R::mutex},"Lock the mutex, optionally for the duration of a callable."),overload({{"body","function<()->opaque>"}},"opaque")),
        call("mutex.unlock","method","concurrency","mutex",overload({},"void"),{},{R::mutex},"Unlock the mutex."),
        call("thread.join","method","concurrency","thread",overload({},"void"),{"ThreadError"},{R::threading},"Join the thread and propagate a worker failure."),
        call("thread.joinable","method","concurrency","thread",overload({},"bool"),{},{R::threading},"Report whether the thread can be joined."),
        call("cancellation_source.token","method","concurrency","cancellation_source",overload({},"cancellation_token"),{},{R::cancellation},"Create a copyable observer for this cancellation state."),
        call("cancellation_source.cancel","method","concurrency","cancellation_source",overload({},"void"),{},{R::cancellation},"Request cancellation once and wake all observers."),
        call("cancellation_token.cancelled","method","concurrency","cancellation_token",overload({},"bool"),{},{R::cancellation},"Report whether cancellation was requested."),
        call("cancellation_token.wait","method","concurrency","cancellation_token",overload({},"void"),{},{R::cancellation},"Wait without busy-spinning until cancellation is requested."),
        call("cancellation_token.throw_if_cancelled","method","concurrency","cancellation_token",overload({},"void"),{"CancellationError"},{R::cancellation},"Raise CancellationError when cancellation was requested."),
        call("bytes.from_string","method","core","bytes",overload({{"value","string"}},"bytes"),{},{R::bytes},"Copy the exact string code units into a byte value without UTF-8 validation."),
        call("bytes.to_string","method","core","bytes",overload({},"string"),{},{R::bytes},"Copy the exact bytes into a string without UTF-8 validation."),
        call("bytes.length","method","core","bytes",overload({},"int_64"),{},{R::bytes},"Return the number of bytes."),
        call("bytes.empty","method","core","bytes",overload({},"bool"),{},{R::bytes},"Report whether the value contains no bytes."),
        call("bytes.slice","method","core","bytes",overload({{"begin","int_64"},{"end","int_64"}},"bytes"),{},{R::bytes},"Copy a half-open byte range."),
        call("process_in.write","method","process","process_in",overload({{"data","string"}},"void"),{"ExecError"},{R::process},"Write to process standard input."),
        call("process_in.write_bytes","method","process","process_in",overload({{"data","bytes"}},"void"),{"ExecError"},{R::process},"Write all bytes to process standard input."),
        call("process_in.flush","method","process","process_in",overload({},"void"),{},{R::process},"Complete an unbuffered process-pipe flush."),
        call("process_in.write_line","method","process","process_in",overload({{"data","string"}},"void"),{"ExecError"},{R::process},"Write a line to process standard input."),
        call("process_in.close","method","process","process_in",overload({},"void"),{},{R::process},"Close process standard input."),
        call("process_out.read","method","process","process_out",overload({{"count","int"}},"string"),{"ExecError"},{R::process},"Read bytes from a process output pipe."),
        call("process_out.read_bytes","method","process","process_out",overload({{"max_bytes","int_64"}},"bytes"),{"ExecError"},{R::process},"Read at most the requested bytes from a process output pipe."),
        call("process_out.read_all_bytes","method","process","process_out",optional_last(overload({{"limit","int_64"}},"bytes")),{"ExecError"},{R::process},"Read the remaining process output bytes up to an optional hard limit."),
        call("process_out.read_line","method","process","process_out",overload({},"string"),{"ExecError"},{R::process},"Read a line from a process output pipe."),
        call("process_out.read_all","method","process","process_out",overload({},"string"),{"ExecError"},{R::process},"Read the remaining process output."),
        call("process_out.eof","method","process","process_out",overload({},"bool"),{},{R::process},"Report whether process output reached end of file."),
        call("process_out.close","method","process","process_out",overload({},"void"),{},{R::process},"Close a process output pipe."),
        call("process.wait","method","process","process",overload({},"int"),{"ExecError"},{R::process},"Wait for the direct process, dispose remaining members of its owned group or Job, and return its exit code."),
        call("process.terminate","method","process","process",overload({},"void"),{"ExecError"},{R::process},"Request termination of the owned POSIX process group or Windows Job."),
        call("process.running","method","process","process",overload({},"bool"),{},{R::process},"Report whether the process is running."),
        call("process.exit_code","method","process","process",overload({},"int"),{},{R::process},"Return the exit code, or -1 while running."),
        call("process.close_input","method","process","process",overload({},"void"),{},{R::process},"Close process standard input."),
        call("pty.read_bytes","method","pty","pty",overload({{"max_bytes","int_64"}},"bytes"),{"PtyError"},{R::pty},"Read at most the requested binary bytes from the pseudo-terminal."),
        call("pty.write_bytes","method","pty","pty",overload({{"data","bytes"}},"void"),{"PtyError"},{R::pty},"Write all bytes to the pseudo-terminal or fail."),
        call("pty.eof","method","pty","pty",overload({},"bool"),{},{R::pty},"Report whether slave closure has been observed."),
        call("pty.resize","method","pty","pty",overload({{"rows","int"},{"columns","int"}},"void"),{"PtyError"},{R::pty},"Set terminal dimensions from 1 through 65535 and let the kernel deliver SIGWINCH."),
        call("pty.interrupt","method","pty","pty",overload({},"void"),{"PtyError"},{R::pty},"Send SIGINT to the validated foreground process group, or the pinned leader group."),
        call("pty.terminate","method","pty","pty",overload({},"void"),{"PtyError"},{R::pty},"Send SIGTERM to the validated foreground process group, or the pinned leader group."),
        call("pty.kill","method","pty","pty",overload({},"void"),{"PtyError"},{R::pty},"Send SIGKILL to the validated foreground process group, or the pinned leader group."),
        call("pty.hangup","method","pty","pty",overload({},"void"),{"PtyError"},{R::pty},"Send SIGHUP to the validated foreground process group, or the pinned leader group."),
        call("pty.wait","method","pty","pty",overload({},"int"),{"PtyError"},{R::pty},"Wait cancellably for the session leader, clean up its original process group, and return its cached exit code."),
        call("pty.running","method","pty","pty",overload({},"bool"),{},{R::pty},"Report whether the PTY child is running."),
        call("pty.exit_code","method","pty","pty",overload({},"int"),{},{R::pty},"Return the exit code, or -1 while running."),
        call("pty.close","method","pty","pty",overload({},"void"),{},{R::pty},"Idempotently close the terminal and perform bounded cleanup of the session leader's original process group."),
        call("istream.read_bytes","method","streams","istream",overload({{"max_bytes","int_64"}},"bytes"),{"StreamError"},{R::io},"Read at most the requested bytes from an input stream."),
        call("istream.read_all_bytes","method","streams","istream",optional_last(overload({{"limit","int_64"}},"bytes")),{"StreamError"},{R::io},"Read the remaining bytes up to an optional hard limit."),
        call("istream.eof","method","streams","istream",overload({},"bool"),{},{R::io},"Report whether end of input has been observed."),
        call("istream.close","method","streams","istream",overload({},"void"),{},{R::io},"Close the input stream wrapper."),
        call("ostream.write","method","streams","ostream",overload({{"data","string"}},"void"),{"StreamError"},{R::io},"Write text to an output stream."),
        call("ostream.write_bytes","method","streams","ostream",overload({{"data","bytes"}},"void"),{"StreamError"},{R::io},"Write all bytes or fail."),
        call("ostream.flush","method","streams","ostream",overload({},"void"),{"StreamError"},{R::io},"Flush an output stream; flushing a closed wrapper is a no-op."),
        call("ostream.close","method","streams","ostream",overload({},"void"),{},{R::io},"Close the output stream wrapper."),
        call("ofstream.open","method","streams","ofstream",optional_last(overload({{"path","string"},{"binary","bool"}},"void")),{"StreamError"},{R::io},"Open a file for output."),
        call("ofstream.close","method","streams","ofstream",overload({},"void"),{"StreamError"},{R::io},"Close an output file."),
        call("ofstream.write","method","streams","ofstream",overload({{"data","string"}},"void"),{"StreamError"},{R::io},"Write text to an output file."),
        call("ofstream.write_bytes","method","streams","ofstream",overload({{"data","bytes"}},"void"),{"StreamError"},{R::io},"Write all bytes to an output file or fail."),
        call("ofstream.flush","method","streams","ofstream",overload({},"void"),{"StreamError"},{R::io},"Flush an output file; flushing after close is a no-op."),
        call("ofstream.is_open","method","streams","ofstream",overload({},"bool"),{},{R::io},"Report whether an output file is open."),
        call("ifstream.open","method","streams","ifstream",optional_last(overload({{"path","string"},{"binary","bool"}},"void")),{"StreamError"},{R::io},"Open a file for input."),
        call("ifstream.close","method","streams","ifstream",overload({},"void"),{},{R::io},"Close an input file."),
        call("ifstream.read_all","method","streams","ifstream",overload({},"string"),{"StreamError"},{R::io},"Read the complete input file."),
        call("ifstream.read_bytes","method","streams","ifstream",overload({{"max_bytes","int_64"}},"bytes"),{"StreamError"},{R::io},"Read at most the requested bytes from an input file."),
        call("ifstream.read_all_bytes","method","streams","ifstream",optional_last(overload({{"limit","int_64"}},"bytes")),{"StreamError"},{R::io},"Read the remaining file bytes up to an optional hard limit."),
        call("ifstream.eof","method","streams","ifstream",overload({},"bool"),{},{R::io},"Report whether end of file has been observed."),
        call("ifstream.is_open","method","streams","ifstream",overload({},"bool"),{},{R::io},"Report whether an input file is open."),
        call("sstream.write","method","streams","sstream",overload({{"data","string"}},"void"),{"StreamError"},{R::io},"Write text to a string stream."),
        call("sstream.write_bytes","method","streams","sstream",overload({{"data","bytes"}},"void"),{"StreamError"},{R::io},"Write all bytes to a string stream or fail."),
        call("sstream.flush","method","streams","sstream",overload({},"void"),{"StreamError"},{R::io},"Flush a string stream; flushing after close is a no-op."),
        call("sstream.str","method","streams","sstream",overload({},"string"),{},{R::io},"Return the string stream contents."),
        call("sstream.read_all","method","streams","sstream",overload({},"string"),{},{R::io},"Return the string stream contents."),
        call("sstream.is_open","method","streams","sstream",overload({},"bool"),{},{R::io},"Report whether the string stream is open."),
        call("sstream.close","method","streams","sstream",overload({},"void"),{},{R::io},"Close the string stream."),
        call("http_response.json","method","http","http_response",overload({},"json"),{"HttpError"},{R::http_client,R::json},"Parse the response body as JSON."),
        call("http_values.get","method","http","http_values",overload({{"name","string"}},"string?"),{},{R::http_server},"Return the first value for a name, or null when absent."),
        call("http_values.values","method","http","http_values",overload({{"name","string"}},"string[]"),{},{R::http_server},"Return every value for a name in wire order."),
        call("http_values.has","method","http","http_values",overload({{"name","string"}},"bool"),{},{R::http_server},"Report whether a name has at least one value."),
        call("http_request.text","method","http","http_request",optional_last(overload({{"limit","int_64"}},"string")),{"HttpError"},{R::http_server},"Return the buffered request body within an optional byte limit."),
        call("http_request.json","method","http","http_request",optional_last(overload({{"limit","int_64"}},"json")),{"HttpError"},{R::http_server,R::json},"Parse the buffered request body as JSON within an optional byte limit."),
        call("http_request.form","method","http","http_request",optional_last(overload({{"limit","int_64"}},"http_values")),{"HttpError"},{R::http_server},"Parse a buffered application/x-www-form-urlencoded body with repeated values preserved."),
        call("sqlite_db.query","method","sqlite","sqlite_db",optional_last(overload({{"sql","string"},{"parameters","json"}},"json")),{"SqliteError"},{R::sqlite},"Execute a query and return rows as JSON."),
        call("sqlite_db.exec","method","sqlite","sqlite_db",optional_last(overload({{"sql","string"},{"parameters","json"}},"void")),{"SqliteError"},{R::sqlite},"Execute a SQL statement."),
        call("sqlite_db.close","method","sqlite","sqlite_db",overload({},"void"),{},{R::sqlite},"Close the database."),
        call("sqlite_db.transaction","method","sqlite","sqlite_db",overload({{"body","function<()->void>"}},"void"),{"SqliteError"},{R::sqlite},"Run a callable in a transaction."),
        call("http_server.listen","method","http","http_server",optional_last(overload({{"host","string"},{"port","int"},{"max_requests","int"}},"void")),{"NetworkError"},{R::http_server},"Listen for HTTP connections using bounded reusable workers."),
        call("http_server.listen_tls","method","http","http_server",optional_last(overload({{"host","string"},{"port","int"},{"certificate","string"},{"private_key","string"},{"max_requests","int"}},"void")),{"NetworkError","TlsError"},{R::http_server_tls},"Listen for HTTPS connections with bounded handshakes and a PEM certificate chain and matching private key."),
        call("http_server.stop","method","http","http_server",overload({},"void"),{},{R::http_server},"Stop admission and drain requests against one configured shutdown deadline."),
        call("http_server.running","method","http","http_server",overload({},"bool"),{},{R::http_server},"Report whether the server is accepting or draining requests."),
        call("http_server.timeouts","method","http","http_server",overload({{"read_ms","int"},{"write_ms","int"},{"idle_ms","int"},{"shutdown_ms","int"}},"void"),{"NetworkError"},{R::http_server},"Configure explicit request I/O, idle, and graceful-shutdown timeouts."),
        call("http_server.limits","method","http","http_server",overload({{"body_bytes","int_64"},{"header_bytes","int_64"},{"header_count","int"},{"connections","int"}},"void"),{"NetworkError"},{R::http_server},"Configure request body, header, and total admitted-connection limits."),
        call("http_server.websocket_limits","method","http","http_server",overload({{"frame_bytes","int_64"},{"message_bytes","int_64"}},"void"),{"NetworkError"},{R::http_websocket},"Configure WebSocket data-frame and reassembled-message payload limits while stopped."),
        call("http_server.get","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request)->http_server_response>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP GET route."),
        call("http_server.post","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request)->http_server_response>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP POST route."),
        call("http_server.get_stream","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request,http_response_writer)->void>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP GET route with an incremental response writer."),
        call("http_server.post_stream","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request,http_response_writer)->void>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP POST route with an incremental response writer."),
        call("http_server.get_request_stream","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request,http_request_body,http_response_writer)->void>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP GET route with a streaming request body and response writer."),
        call("http_server.post_request_stream","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request,http_request_body,http_response_writer)->void>"}},"void"),{"NetworkError"},{R::http_server},"Register an HTTP POST route with a streaming request body and response writer."),
        call("http_server.websocket","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request,websocket)->void>"}},"void"),{"NetworkError"},{R::http_websocket},"Register a synchronous RFC 6455 WebSocket upgrade route."),
        call("websocket.accept","method","http","websocket",optional_last(overload({{"subprotocol","string"}},"void")),{"NetworkError"},{R::http_websocket},"Accept the pending WebSocket upgrade, optionally selecting one offered subprotocol."),
        call("websocket.read","method","http","websocket",overload({},"websocket_message?"),{"WebSocketError","NetworkError"},{R::http_websocket},"Read and reassemble the next text or binary message, or return null after peer close."),
        call("websocket.read_text","method","http","websocket",overload({},"string?"),{"WebSocketError","NetworkError"},{R::http_websocket},"Read the next text message without discarding a mismatched binary message."),
        call("websocket.read_bytes","method","http","websocket",overload({},"bytes?"),{"WebSocketError","NetworkError"},{R::http_websocket},"Read the next binary message without discarding a mismatched text message."),
        call("websocket.write_text","method","http","websocket",overload({{"text","string"}},"void"),{"WebSocketError","NetworkError"},{R::http_websocket},"Write one validated UTF-8 text message with synchronous backpressure."),
        call("websocket.write_bytes","method","http","websocket",overload({{"data","bytes"}},"void"),{"WebSocketError","NetworkError"},{R::http_websocket},"Write one binary message with synchronous backpressure."),
        with_overload(call("websocket.ping","method","http","websocket",overload({},"void"),{"WebSocketError","NetworkError"},{R::http_websocket},"Write a ping control frame with an optional payload."),overload({{"payload","bytes"}},"void")),
        with_overload(with_overload(call("websocket.close","method","http","websocket",overload({},"void"),{"WebSocketError","NetworkError"},{R::http_websocket},"Send one validated server close frame; code 1010 is rejected and repeated calls are harmless."),overload({{"code","int"}},"void")),overload({{"code","int"},{"reason","string"}},"void")),
        call("http_server.get_async","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request)->future<http_server_response>>"}},"void"),{"NetworkError"},{R::http_server,R::async},"Register an asynchronous HTTP GET route."),
        call("http_server.post_async","method","http","http_server",overload({{"route","string"},{"handler","function<(http_request)->future<http_server_response>>"}},"void"),{"NetworkError"},{R::http_server,R::async},"Register an asynchronous HTTP POST route."),
        call("http_server.static","method","http","http_server",optional_last(overload({{"prefix","string"},{"files","map<string,string>"},{"fallback","string"}},"void")),{"NetworkError"},{R::http_server},"Serve embedded static files under a route prefix."),
        call("http_response_writer.status","method","http","http_response_writer",overload({{"status","int"}},"void"),{"NetworkError"},{R::http_server},"Set the response status before commitment."),
        call("http_response_writer.header","method","http","http_response_writer",overload({{"name","string"},{"value","string"}},"void"),{"NetworkError"},{R::http_server},"Add a validated custom response header before commitment."),
        call("http_response_writer.cookie","method","http","http_response_writer",overload({{"value","http_cookie"}},"void"),{"NetworkError"},{R::http_server},"Append a validated Set-Cookie field before commitment."),
        call("http_response_writer.content_type","method","http","http_response_writer",overload({{"value","string"}},"void"),{"NetworkError"},{R::http_server},"Set the validated response media type before commitment."),
        call("http_response_writer.content_length","method","http","http_response_writer",overload({{"length","int_64"}},"void"),{"NetworkError"},{R::http_server},"Declare an exact response length for transport-owned framing."),
        call("http_response_writer.write","method","http","http_response_writer",overload({{"data","string"}},"void"),{"NetworkError"},{R::http_server},"Write text incrementally using the selected HTTP framing."),
        call("http_response_writer.write_bytes","method","http","http_response_writer",overload({{"data","bytes"}},"void"),{"NetworkError"},{R::http_server},"Write binary data incrementally using the selected HTTP framing."),
        call("http_response_writer.flush","method","http","http_response_writer",overload({},"void"),{"NetworkError"},{R::http_server},"Commit response metadata and flush pending HTTP framing."),
        call("http_response_writer.finish","method","http","http_response_writer",overload({},"void"),{"NetworkError"},{R::http_server},"Finish the response exactly once; repeated finish calls are harmless."),
        call("http_request_body.read_bytes","method","http","http_request_body",overload({{"max_bytes","int_64"}},"bytes"),{"NetworkError"},{R::http_server},"Read at most the requested decoded request-body bytes."),
        call("http_request_body.read_all_bytes","method","http","http_request_body",optional_last(overload({{"limit","int_64"}},"bytes")),{"NetworkError"},{R::http_server},"Read the remaining decoded request body up to an optional hard limit."),
        call("http_request_body.eof","method","http","http_request_body",overload({},"bool"),{},{R::http_server},"Report whether the validated request-body framing reached its terminal state."),
        call("http_request_body.close","method","http","http_request_body",overload({},"void"),{},{R::http_server},"Close the request body reader; later reads fail."),
        call("tcp_socket.read","method","networking","tcp_socket",optional_last(overload({{"max_bytes","int_64"}},"string")),{"NetworkError"},{R::networking},"Read from a TCP socket."),
        call("tcp_socket.write","method","networking","tcp_socket",overload({{"data","string"}},"void"),{"NetworkError"},{R::networking},"Write to a TCP socket."),
        call("tcp_socket.close","method","networking","tcp_socket",overload({},"void"),{},{R::networking},"Close a TCP socket."),
        call("tcp_socket.is_open","method","networking","tcp_socket",overload({},"bool"),{},{R::networking},"Report whether a TCP socket is open."),
        call("tcp_listener.accept","method","networking","tcp_listener",overload({},"tcp_socket"),{"NetworkError"},{R::networking},"Accept a TCP connection."),
        call("tcp_listener.accept_async","method","networking","tcp_listener",overload({},"future<tcp_socket>"),{"NetworkError"},{R::networking,R::async},"Accept a TCP connection asynchronously."),
        call("tcp_listener.close","method","networking","tcp_listener",overload({},"void"),{},{R::networking},"Close a TCP listener."),
        call("tcp_listener.is_open","method","networking","tcp_listener",overload({},"bool"),{},{R::networking},"Report whether a TCP listener is open."),
        call("tls_stream.read","method","networking","tls_stream",optional_last(overload({{"max_bytes","int_64"}},"string")),{"TlsError"},{R::http_client},"Read from a TLS stream."),
        call("tls_stream.write","method","networking","tls_stream",overload({{"data","string"}},"void"),{"TlsError"},{R::http_client},"Write to a TLS stream."),
        call("tls_stream.close","method","networking","tls_stream",overload({},"void"),{},{R::http_client},"Close a TLS stream."),
        call("tls_stream.is_open","method","networking","tls_stream",overload({},"bool"),{},{R::http_client},"Report whether a TLS stream is open."),
    };
    return items;
}
bool api_owner_matches(std::string_view schema_owner,std::string_view owner){if(schema_owner==owner)return true;const auto wildcard=schema_owner.find("<T>");return wildcard!=std::string_view::npos&&owner.size()>wildcard+2&&owner.substr(0,wildcard+1)==schema_owner.substr(0,wildcard+1)&&owner.back()=='>';}
const ApiCallable* api_callable(std::string_view name,std::string_view owner){for(const auto& item:api_callables()){const auto leaf=item.owner.empty()?item.name:item.name.substr(item.name.find('.')+1);if(leaf==name&&api_owner_matches(item.owner,owner))return &item;}return nullptr;}
const std::vector<ApiField>& api_fields(){static const std::vector<ApiField> value={
    {"exit_code","exec_result",t("int"),"Process exit code."},{"stdout","exec_result",t("string"),"Captured standard output."},{"stderr","exec_result",t("string"),"Captured standard error."},
    {"status","http_response",t("int"),"HTTP response status."},{"body","http_response",t("string"),"HTTP response body."},{"headers","http_response",t("map<string,string>"),"HTTP response headers."},
    {"status","http_response_head",t("int"),"Final HTTP response status."},{"headers","http_response_head",t("map<string,string>"),"Final validated HTTP response headers."},
    {"kind","websocket_message",t("string"),"Message kind: text or binary.",false},{"text","websocket_message",t("string?"),"Text payload for a text message, otherwise null.",false},{"data","websocket_message",t("bytes?"),"Binary payload for a binary message, otherwise null.",false},
    {"method","http_request",t("string"),"HTTP request method."},{"path","http_request",t("string"),"HTTP request path."},{"body","http_request",t("string"),"HTTP request body."},{"headers","http_request",t("map<string,string>"),"HTTP request headers."},{"query","http_request",t("map<string,string>"),"Raw HTTP query parameters using the last value for repeated names."},{"query_values","http_request",t("http_values"),"Decoded HTTP query parameters with repeated values preserved.",false},{"cookies","http_request",t("http_values"),"Validated request cookies with repeated names preserved.",false},{"params","http_request",t("map<string,string>"),"Matched route parameters."},{"cancellation","http_request",t("cancellation_token"),"Read-only token cancelled when this request lifetime ends.",false},
    {"status","http_server_response",t("int"),"Final HTTP response status from 200 through 599."},{"body","http_server_response",t("string"),"HTTP response body."},{"content_type","http_server_response",t("string"),"Validated HTTP response content type."},{"headers","http_server_response",t("map<string,string>"),"Validated custom response headers; transport framing fields and Set-Cookie are reserved."},{"cookies","http_server_response",t("http_cookie[]"),"Ordered structured cookies emitted as distinct Set-Cookie fields."},
    {"name","http_cookie",t("string"),"Cookie name."},{"value","http_cookie",t("string"),"Cookie value."},{"path","http_cookie",t("string?"),"Optional cookie Path attribute."},{"domain","http_cookie",t("string?"),"Optional cookie Domain attribute."},{"max_age","http_cookie",t("int_64?"),"Optional cookie Max-Age in seconds."},{"expires","http_cookie",t("string?"),"Optional cookie Expires value."},{"secure","http_cookie",t("bool"),"Emit the Secure attribute."},{"http_only","http_cookie",t("bool"),"Emit the HttpOnly attribute."},{"same_site","http_cookie",t("string?"),"Optional Strict, Lax, or None SameSite attribute."},
    {"in","process",t("process_in"),"Child standard input."},{"out","process",t("process_out"),"Child standard output."},{"err","process",t("process_out"),"Child standard error."},
};return value;}
const ApiField* api_field(std::string_view name,std::string_view owner){for(const auto& field:api_fields())if(field.name==name&&api_owner_matches(field.owner,owner))return &field;return nullptr;}
const std::vector<std::string>& standard_modules(){static const std::vector<std::string> value={"vector","map","set","ordered_map","ordered_set","queue","stack","deque","list","priority_queue","tuple","filesystem","encoding","crypto"};return value;}
const std::vector<std::string>& api_named_types(){static const std::vector<std::string> value={"http_request","http_request_body","http_values","http_cookie","http_server_response","http_response_writer","http_server","websocket","websocket_message","WebSocketError","SqliteError","sqlite_db","EmbedError","FilesystemError","StreamError","EnvironmentError","TimeError","ExecError","PtyError","exec_result","process","pty","thread","ThreadError","process_in","process_out","mutex","MutexError","CancellationError","cancellation_source","cancellation_token","CryptoError","EncodingError","NetworkError","tcp_socket","tcp_listener","TlsError","tls_stream","HttpError","http_response","http_response_head","istream","ostream","sstream","ifstream","ofstream","bytes"};return value;}
std::string api_signature(const ApiCallable& c,const ApiOverload& o){std::string value=c.owner.empty()?c.name:c.name.substr(c.name.find('.')+1);value+="(";for(std::size_t i=0;i<o.parameters.size();++i){if(i)value+=", ";value+=type_spelling(o.parameters[i].type)+" "+o.parameters[i].name;if(o.parameters[i].optional)value+="?";}return value+") -> "+type_spelling(o.return_type);}
bool api_matches(const ApiCallable& c,std::string_view query){if(query.empty())return true;const auto q=lower(query);if(q=="checked-errors")return !c.checked_errors.empty();return lower(c.name).find(q)!=std::string::npos||lower(c.category).find(q)!=std::string::npos||lower(c.module).find(q)!=std::string::npos||lower(c.owner).find(q)!=std::string::npos||lower(c.summary).find(q)!=std::string::npos;}
} // namespace strut
