#include <cstdlib>
#include <filesystem>
#include <iostream>
#include "strut/codegen.h"
#include "strut/ir.h"
#include "strut/lexer.h"
#include "strut/parser.h"
#include "strut/sema.h"
#include "strut/source.h"
#include "temp_directory.h"
namespace {
void req(bool x,const char*m){if(!x){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);}}
std::size_t occurrences(const std::string& text,const std::string& needle){std::size_t count=0,pos=0;while((pos=text.find(needle,pos))!=std::string::npos){++count;pos+=needle.size();}return count;}
std::filesystem::path native_executable(std::filesystem::path value) {
#ifdef _WIN32
 value += ".exe";
#endif
 return value;
}
}
int main(){TestTempDirectory temp("strut-codegen-test");strut::SourceFile s("hello.p","function add(int a, int b) -> int { return a + b; } function main() -> void { x := add(2,3); print(\"hello \" , x); return; }"); strut::Lexer l(s);auto lx=l.lex();strut::Parser p(lx.tokens);auto a=p.parse();req(a.ok(),"parse");strut::SemanticAnalyzer sem;auto sr=sem.analyze(a.program);req(sr.ok(),"sema");strut::IRLowerer lower;auto ir=lower.lower(a.program);ir.program.source_path="hello.p";strut::CppBackend b;auto g=b.generate(ir.program);req(g.cpp.find("strut_print")!=std::string::npos,"print generated");req(g.cpp.find("#line 1 \"hello.p\"")!=std::string::npos,"source line mapping generated");req(g.cpp.find("json.h")==std::string::npos,"string-only program omits JSONIC");req(g.cpp.find("curl/")==std::string::npos&&g.cpp.find("openssl/")==std::string::npos&&g.cpp.find("sqlite3")==std::string::npos&&g.cpp.find("class strut_tcp_socket")==std::string::npos&&g.cpp.find("class strut_process")==std::string::npos,"hello runtime excludes native subsystems");req(g.cpp.size()<5000,"string-only runtime remains compact");auto out=temp.path()/"program";std::string err;req(b.compile(ir.program,out,err),err.c_str());const auto native_out=native_executable(out);req(std::filesystem::exists(native_out),"native executable");
{ strut::SourceFile ms("minimal.p","function main() -> void { int x := 1; print(x); return; }"); strut::Lexer ml(ms); auto mx=ml.lex(); strut::Parser mp(mx.tokens); auto ma=mp.parse(); req(ma.ok(),"minimal parse"); strut::SemanticAnalyzer msem; auto msr=msem.analyze(ma.program); req(msr.ok(),"minimal sema"); strut::IRLowerer mlower; auto mir=mlower.lower(ma.program); auto mg=b.generate(mir.program); req(mg.cpp.find("json.h")==std::string::npos,"minimal runtime omits JSONIC"); req(mg.cpp.size()<5000,"minimal runtime remains compact"); }
{ strut::SourceFile vs("vec.p","function main() -> void { int[] values := []; values.push(1); print(values.length); return; }"); strut::Lexer vl(vs); auto vx=vl.lex(); strut::Parser vp(vx.tokens); auto va=vp.parse(); req(va.ok(),"vector parse"); strut::SemanticAnalyzer vsem; auto vsr=vsem.analyze(va.program); req(vsr.ok(),"vector sema"); strut::IRLowerer vlower; auto vir=vlower.lower(va.program); auto vg=b.generate(vir.program); req(vg.cpp.find("#include <vector>")!=std::string::npos,"vector runtime includes vector"); req(vg.cpp.find("#include <array>")==std::string::npos,"dynamic vector omits array header"); req(vg.cpp.find("#include <optional>")==std::string::npos,"non-nullable vector omits optional header"); req(vg.cpp.find("#include <type_traits>")==std::string::npos,"simple vector omits type-traits header"); }
{ strut::SourceFile maps("map.p","function main() -> void { int[] values := [1,2]; doubled := values.map((int x) => x * 2); print(doubled.length); return; }"); strut::Lexer ml2(maps); auto mx2=ml2.lex(); strut::Parser mp2(mx2.tokens); auto ma2=mp2.parse(); req(ma2.ok(),"map parse"); strut::SemanticAnalyzer msem2; auto msr2=msem2.analyze(ma2.program); req(msr2.ok(),"map sema"); strut::IRLowerer mlower2; auto mir2=mlower2.lower(ma2.program); auto mg2=b.generate(mir2.program); req(mg2.cpp.find("#include <vector>")!=std::string::npos,"map runtime includes vector"); req(mg2.cpp.find("#include <type_traits>")!=std::string::npos,"map runtime includes type traits"); req(mg2.cpp.find("#include <optional>")==std::string::npos,"map without nullable/find omits optional header"); }
{ strut::SourceFile cs("containers.p","function main() -> void { vector<int> v := [1,2]; map<int,int> m := [1:2]; ordered_map<int,int> om; set<int> s := [1,2]; ordered_set<int> os; queue<int> q; stack<int> st; deque<int> dq; list<int> li; priority_queue<int> pq; priority_queue<int,min> minpq; s.add(3); print(s.contains(3)); m.insert(2,3); return; }"); strut::Lexer cl(cs); auto cx=cl.lex(); strut::Parser cp(cx.tokens); auto ca=cp.parse(); req(ca.ok(),"containers parse"); strut::SemanticAnalyzer csem; auto csr=csem.analyze(ca.program); req(csr.ok(),"containers sema"); strut::IRLowerer clower; auto cir=clower.lower(ca.program); auto cg=b.generate(cir.program); req(cg.cpp.find("#include <unordered_map>")!=std::string::npos,"hash map includes unordered_map"); req(cg.cpp.find("#include <map>")!=std::string::npos,"ordered map includes map"); req(cg.cpp.find("#include <unordered_set>")!=std::string::npos,"hash set includes unordered_set"); req(cg.cpp.find("#include <set>")!=std::string::npos,"ordered set includes set"); req(cg.cpp.find("#include <queue>")!=std::string::npos,"queue/priority queue includes queue"); req(cg.cpp.find("#include <stack>")!=std::string::npos,"stack includes stack"); req(cg.cpp.find("#include <deque>")!=std::string::npos,"deque includes deque"); req(cg.cpp.find("#include <list>")!=std::string::npos,"list includes list"); req(cg.cpp.find("json.h")==std::string::npos,"numeric collections keep minimal runtime"); auto co=temp.path()/"collections"; std::string ce; cir.program.source_path="containers.p"; req(b.compile(cir.program,co,ce),ce.c_str()); }
{ strut::SourceFile pqs("pq.p","function main() -> void { priority_queue<int> q; q.push(1); print(q.top()); return; }"); strut::Lexer pql(pqs); auto pqx=pql.lex(); strut::Parser pqp(pqx.tokens); auto pqa=pqp.parse(); req(pqa.ok(),"priority queue parse"); strut::SemanticAnalyzer pqsem; auto pqsr=pqsem.analyze(pqa.program); req(pqsr.ok(),"priority queue sema"); strut::IRLowerer pqlower; auto pqir=pqlower.lower(pqa.program); auto pqg=b.generate(pqir.program); req(pqg.cpp.find("#include <queue>")!=std::string::npos,"priority queue includes queue"); req(pqg.cpp.find("#include <vector>")==std::string::npos,"max priority queue avoids explicit vector header"); req(pqg.cpp.find("#include <functional>")==std::string::npos,"max priority queue avoids comparator header"); }
{ strut::SourceFile hcs("http-client.p","function main() -> void : HttpError { response := http_get(\"http://127.0.0.1:9/\"); print(response.status); return; }"); strut::Lexer hcl(hcs); auto hcx=hcl.lex(); strut::Parser hcp(hcx.tokens); auto hca=hcp.parse(); req(hca.ok(),"http client parse"); strut::SemanticAnalyzer hcsem; auto hcsr=hcsem.analyze(hca.program); req(hcsr.ok(),"http client sema"); strut::IRLowerer hclower; auto hcir=hclower.lower(hca.program); hcir.program.source_path="http-client.p"; auto hcg=b.generate(hcir.program); req(hcg.cpp.find("#define STRUT_USE_CURL 1")!=std::string::npos,"sync HTTP client enables curl"); req(hcg.cpp.find("openssl/")==std::string::npos,"HTTP client omits direct OpenSSL runtime"); req(hcg.cpp.find("strut_http_server")==std::string::npos,"sync HTTP client omits server runtime"); req(hcg.cpp.find("strut_executor")==std::string::npos,"sync HTTP client omits async executor"); req(occurrences(hcg.cpp,"struct strut_http_response {")==1,"HTTP client implementation emitted once"); req(hcg.cpp.size()<18000,"sync HTTP client runtime remains sliced"); std::string hce;req(b.compile(hcir.program,temp.path()/"http-client",hce),hce.c_str()); }
{ strut::SourceFile hjs("http-json.p","function main() -> void : HttpError { body := http_get_json(\"https://example.com\"); print(body[\"name\"]); return; }");strut::Lexer hjl(hjs);auto hjx=hjl.lex();strut::Parser hjp(hjx.tokens);auto hja=hjp.parse();req(hja.ok(),"http JSON parse");strut::SemanticAnalyzer hjsem;auto hjsr=hjsem.analyze(hja.program);req(hjsr.ok(),"http JSON sema");strut::IRLowerer hjlower;auto hjir=hjlower.lower(hja.program);auto hjg=b.generate(hjir.program);req(hjg.cpp.find("json::Document body = http_get_json")!=std::string::npos&&hjg.cpp.find("strut_print(body[\"name\"])")!=std::string::npos,"HTTP JSON indexes as JSON rather than native container");}
{ strut::SourceFile js("json-stream.p","operator <<(ostream& sink, json value) -> ostream& { return sink; } function main() -> void { payload := {\"value\": 1}; print(payload); return; }");strut::Lexer jl(js);auto jx=jl.lex();strut::Parser jp(jx.tokens);auto ja=jp.parse();req(ja.ok(),"JSON stream parse");strut::SemanticAnalyzer jsem;auto jsr=jsem.analyze(ja.program);req(jsr.ok(),"JSON stream sema");strut::IRLowerer jlower;auto jir=jlower.lower(ja.program);jir.program.source_path="json-stream.p";std::string je;req(b.compile(jir.program,temp.path()/"json-stream",je),je.c_str());}
{ strut::SourceFile gis("generic-array.p","function identity[T](T value) -> T { return value; } function main() -> void { int[] values := identity([1,2,3]); print(values.length); return; }");strut::Lexer gil(gis);auto gix=gil.lex();strut::Parser gip(gix.tokens);auto gia=gip.parse();req(gia.ok(),"generic array parse");strut::SemanticAnalyzer gisem;auto gisr=gisem.analyze(gia.program);req(gisr.ok(),"generic array sema");strut::IRLowerer gilower;auto giir=gilower.lower(gia.program);auto gig=b.generate(giir.program);req(gig.cpp.find("identity(std::vector<std::int32_t>{1,2,3})")!=std::string::npos,"array literal call argument carries concrete vector type");}
{ strut::IRProgram native;auto call=std::make_unique<strut::IRStmt>();call->value=std::make_unique<strut::IRExpr>();call->value->kind=strut::IRExpr::Kind::identifier;call->value->text="http_get";native.statements.push_back(std::move(call));const auto guidance=strut::classify_native_failure(native,"linking");req(guidance.find("native linking failed")!=std::string::npos&&guidance.find("required native library curl")!=std::string::npos&&guidance.find("secondary detail")!=std::string::npos,"native dependency failures are actionable");}
{ strut::SourceFile ps("ptr.p","function read(int* p) -> int { return *p; } function replace(int* p) -> void { p = new(2); return; }"); strut::Lexer pl(ps); auto px=pl.lex(); strut::Parser pp(px.tokens); auto pa=pp.parse(); req(pa.ok(),"ptr parse"); strut::SemanticAnalyzer psem; auto psr=psem.analyze(pa.program); req(psr.ok(),"ptr sema"); strut::IRLowerer lower2; auto pir=lower2.lower(pa.program); auto pg=b.generate(pir.program); req(pg.cpp.find("const std::shared_ptr<std::int32_t>& p")!=std::string::npos,"read-only ptr parameter borrowed"); req(pg.cpp.find("std::shared_ptr<std::int32_t> p")!=std::string::npos,"assigned ptr parameter remains owning value"); req(pg.cpp.find("#include <optional>")==std::string::npos,"non-nullable pointer runtime omits optional header"); }
{ strut::SourceFile fs("fs.p","function main() -> void : FilesystemError { bool x := exists(\".\"); print(x); return; }"); strut::Lexer fl(fs); auto fx=fl.lex(); strut::Parser fp(fx.tokens); auto fa=fp.parse(); req(fa.ok(),"filesystem parse"); strut::SemanticAnalyzer fsem; auto fsr=fsem.analyze(fa.program); req(fsr.ok(),"filesystem sema"); strut::IRLowerer flower; auto fir=flower.lower(fa.program); fir.program.standard_modules={"filesystem"}; auto fg=b.generate(fir.program); req(fg.cpp.find("json.h")==std::string::npos,"filesystem runtime omits JSONIC"); req(fg.cpp.size()<25000,"filesystem runtime remains sliced"); }
{ strut::SourceFile hs("http.p","function main() -> void : NetworkError { http_server app := http_server(); app.get(\"/\", (http_request req) => { return http_text(\"ok\"); }); app.get_stream(\"/stream\", (http_request req, http_response_writer writer) => { writer.write(\"ok\"); writer.finish(); }); return; }"); strut::Lexer hl(hs); auto hx=hl.lex(); strut::Parser hp(hx.tokens); auto ha=hp.parse(); req(ha.ok(),"http parse"); strut::SemanticAnalyzer hsem; auto hsr=hsem.analyze(ha.program); req(hsr.ok(),"http sema"); strut::IRLowerer hlower; auto hir=hlower.lower(ha.program);hir.program.source_path="http.p"; auto hg=b.generate(hir.program); req(hg.cpp.find("json.h")==std::string::npos,"server-only HTTP runtime omits JSONIC"); req(hg.cpp.find("curl/")==std::string::npos&&hg.cpp.find("openssl/")==std::string::npos,"plain HTTP server omits curl and OpenSSL"); req(hg.cpp.find("strut_http_server_legacy")==std::string::npos,"legacy HTTP server is not emitted"); req(occurrences(hg.cpp,"class strut_tcp_socket {")==1&&occurrences(hg.cpp,"class strut_http_server {")==1,"plain server implementations emitted once");req(occurrences(hg.cpp,"strut_parse_http_request_head")==2&&hg.cpp.find("strut_http_header_field")!=std::string::npos,"strict HTTP framing parser emitted once and used");req(occurrences(hg.cpp,"worker_loop")==2&&hg.cpp.find("struct run_state")!=std::string::npos&&hg.cpp.find("active_sockets")==std::string::npos,"bounded reusable HTTP worker pool emitted");req(hg.cpp.find("workers.size()<static_cast<std::size_t>(s->max_connections)")!=std::string::npos&&hg.cpp.find("run->connections.erase(found)")!=std::string::npos,"worker and connection history remains bounded");req(hg.cpp.find("s->current=run;s->phase=lifecycle_phase::starting")<hg.cpp.find("listener=tcp_listen(host,port)"),"pending generation published before blocking startup");req(occurrences(hg.cpp,"strut_serialize_http_response_head")==2&&occurrences(hg.cpp,"class strut_http_response_writer")==1,"buffered and streaming responses share one response state machine"); req(hg.cpp.size()<80000,"server-only HTTP runtime remains sliced");std::string he;req(b.compile(hir.program,temp.path()/"http-server",he),he.c_str()); }
{ strut::SourceFile tls("https.p","function main() -> void : (NetworkError, TlsError) { app := http_server(); app.listen_tls(\"127.0.0.1\", 8443, \"certificate.pem\", \"key.pem\", 1); return; }");strut::Lexer tl(tls);auto tx=tl.lex();strut::Parser tp(tx.tokens);auto ta=tp.parse();req(ta.ok(),"TLS server parse");strut::SemanticAnalyzer tsem;auto tsr=tsem.analyze(ta.program);req(tsr.ok(),"TLS server sema");strut::IRLowerer tlower;auto tir=tlower.lower(ta.program);tir.program.source_path="https.p";auto tg=b.generate(tir.program);req(tg.cpp.find("#include <openssl/ssl.h>")!=std::string::npos&&tg.cpp.find("#include <openssl/err.h>")!=std::string::npos,"TLS server includes OpenSSL");req(tg.cpp.find("#include <curl/curl.h>")==std::string::npos,"TLS server omits curl");req(tg.cpp.find("strut_http_server_legacy")==std::string::npos&&occurrences(tg.cpp,"class strut_http_server {")==1,"TLS server emits only active server");req(occurrences(tg.cpp,"strut_parse_http_request_head")==2,"TLS server uses the shared strict parser");req(tg.cpp.find("SSL_write(ssl_,data.v.data()+offset,amount)")!=std::string::npos,"TLS writes are bounded by the native int limit");std::string te;req(b.compile(tir.program,temp.path()/"https-server",te),te.c_str());}
{ strut::SourceFile sq("sqlite.p","function emit(ostream sink) -> void { sink << \"value\"; return; } function main() -> void : SqliteError { db := sqlite_open(\":memory:\"); db.close(); return; }");strut::Lexer sl(sq);auto sx=sl.lex();strut::Parser sp(sx.tokens);auto sa=sp.parse();req(sa.ok(),"SQLite parse");strut::SemanticAnalyzer ssem;auto ssr=ssem.analyze(sa.program);req(ssr.ok(),"SQLite sema");strut::IRLowerer slower;auto sir=slower.lower(sa.program);sir.program.source_path="sqlite.p";auto sg=b.generate(sir.program);req(sg.cpp.find("#include <sqlite3.h>")!=std::string::npos,"SQLite runtime emitted");req(sg.cpp.find("curl/")==std::string::npos&&sg.cpp.find("class strut_http_server")==std::string::npos&&sg.cpp.find("struct strut_http_response")==std::string::npos,"SQLite runtime excludes HTTP");std::string se;req(b.compile(sir.program,temp.path()/"sqlite",se),se.c_str());}
{ strut::SourceFile ls("http-lifecycle.p","function main() -> void : NetworkError { app := http_server(); app.timeouts(1000, 1000, 1000, 500); app.limits(1024, 4096, 20, 8); if (app.running()) { app.stop(); } return; }");strut::Lexer ll(ls);auto lx=ll.lex();strut::Parser lp(lx.tokens);auto la=lp.parse();req(la.ok(),"HTTP lifecycle parse");strut::SemanticAnalyzer lsem;auto lsr=lsem.analyze(la.program);req(lsr.ok(),"HTTP lifecycle sema");strut::IRLowerer llower;auto lir=llower.lower(la.program);auto lg=b.generate(lir.program);req(lg.cpp.find("void stop() const")!=std::string::npos&&lg.cpp.find("Payload Too Large")!=std::string::npos,"HTTP lifecycle runtime emitted");}
{ strut::SourceFile fsp("fs-path.p","function main() -> void : FilesystemError { print(filename(\"a/b.txt\")); return; }"); strut::Lexer fpl(fsp); auto fpx=fpl.lex(); strut::Parser fpp(fpx.tokens); auto fpa=fpp.parse(); req(fpa.ok(),"filesystem path parse"); strut::SemanticAnalyzer fpsem; auto fpsr=fpsem.analyze(fpa.program); req(fpsr.ok(),"filesystem path sema"); strut::IRLowerer fplower; auto fpir=fplower.lower(fpa.program); fpir.program.standard_modules={"filesystem"}; auto fpg=b.generate(fpir.program); req(fpg.cpp.find("strut_fs_wildcard_match")==std::string::npos,"path-only filesystem omits wildcard machinery"); req(fpg.cpp.find("strut_fs_read_file")==std::string::npos,"path-only filesystem omits file IO"); }
{ strut::SourceFile as("async.p","async function twice(int x) -> int { return x * 2; } function main() -> void { pending := twice(2); print(await pending); return; }"); strut::Lexer al(as); auto ax=al.lex(); strut::Parser ap(ax.tokens); auto aa=ap.parse(); req(aa.ok(),"async parse"); strut::SemanticAnalyzer asem; auto asr=asem.analyze(aa.program); req(asr.ok(),"async sema"); strut::IRLowerer alower; auto air=alower.lower(aa.program); auto ag=b.generate(air.program); req(ag.cpp.find("json.h")==std::string::npos,"async runtime omits JSONIC"); req(ag.cpp.size()<12000,"async runtime remains sliced"); }
{ strut::SourceFile ts("thread.p","function main() -> void : ThreadError { int* result := new(0); worker := thread(() => { *result = 7; print(\"work\"); }); worker.join(); print(*result); return; }");strut::Lexer tl(ts);auto tx=tl.lex();strut::Parser tp(tx.tokens);auto ta=tp.parse();req(ta.ok(),"thread parse");strut::SemanticAnalyzer tsem;auto tsr=tsem.analyze(ta.program);req(tsr.ok(),"thread sema");strut::IRLowerer tlower;auto tir=tlower.lower(ta.program);auto tg=b.generate(tir.program);req(tg.cpp.find("class strut_thread")!=std::string::npos,"thread runtime emitted");req(tg.cpp.find("struct strut_string")!=std::string::npos,"thread lambda string runtime emitted");req(tg.cpp.find("json.h")==std::string::npos,"thread-only runtime omits JSONIC");req(tg.cpp.find("strut_executor")==std::string::npos,"thread-only runtime omits async executor");req(tg.cpp.size()<12000,"thread-only runtime remains sliced");}
{ strut::SourceFile ts("thread-stream.p","function emit(ostream sink) -> void { sink << \"work\"; return; } function main() -> void : ThreadError { worker := thread(() => { return; }); worker.join(); return; }");strut::Lexer tl(ts);auto tx=tl.lex();strut::Parser tp(tx.tokens);auto ta=tp.parse();req(ta.ok(),"thread stream parse");strut::SemanticAnalyzer tsem;auto tsr=tsem.analyze(ta.program);req(tsr.ok(),"thread stream sema");strut::IRLowerer tlower;auto tir=tlower.lower(ta.program);tir.program.source_path="thread-stream.p";std::string te;req(b.compile(tir.program,temp.path()/"thread-stream",te),te.c_str());}
{ strut::SourceFile ats("atomic.p","atomic<int> count := 0; function main() -> int { count.fetch_add(1); return count.load(); }");strut::Lexer atl(ats);auto atx=atl.lex();strut::Parser atp(atx.tokens);auto ata=atp.parse();req(ata.ok(),"atomic parse");strut::SemanticAnalyzer atsem;auto atsr=atsem.analyze(ata.program);req(atsr.ok(),"atomic sema");strut::IRLowerer atlower;auto atir=atlower.lower(ata.program);auto atg=b.generate(atir.program);req(atg.cpp.find("class strut_atomic")!=std::string::npos,"atomic runtime emitted");req(atg.cpp.find("json.h")==std::string::npos,"atomic runtime omits JSONIC");req(atg.cpp.find("strut_executor")==std::string::npos,"atomic runtime omits async executor");req(atg.cpp.size()<12000,"atomic runtime remains sliced");}
{ strut::SourceFile das("direct-async.p","async function answer() -> int { return 42; } function main() -> int { print(await answer()); return 0; }");strut::Lexer dal(das);auto dax=dal.lex();strut::Parser dap(dax.tokens);auto daa=dap.parse();req(daa.ok(),"direct await parse");strut::SemanticAnalyzer dasem;auto dasr=dasem.analyze(daa.program);req(dasr.ok(),"direct await sema");strut::IRLowerer dalower;auto dair=dalower.lower(daa.program);dair.program.source_path="direct-async.p";auto dao=temp.path()/"direct-async";std::string dae;req(b.compile(dair.program,dao,dae),dae.c_str());}
{ strut::SourceFile ns("nested-function.p","function main() -> void { vector<function<(int)->int>> callbacks := []; return; }");strut::Lexer nl(ns);auto nx=nl.lex();strut::Parser np(nx.tokens);auto na=np.parse();req(na.ok(),"nested function type parse");strut::SemanticAnalyzer nsem;auto nsr=nsem.analyze(na.program);req(nsr.ok(),"nested function type sema");strut::IRLowerer nlower;auto nir=nlower.lower(na.program);auto ng=b.generate(nir.program);req(ng.cpp.find("std::vector<std::function<std::int32_t(std::int32_t)>> callbacks")!=std::string::npos,"nested function TypeId lowers structurally");}
auto bytes_minimal=[&](const std::string& body){strut::SourceFile source("bytes-slice.p","function main() -> void { "+body+" return; }");strut::Lexer lexer(source);auto lexed=lexer.lex();strut::Parser parser(lexed.tokens);auto parsed=parser.parse();if(!parsed.ok())return false;strut::SemanticAnalyzer analyzer;auto semantic=analyzer.analyze(parsed.program);if(!semantic.ok())return false;strut::IRLowerer lowerer;auto lowered=lowerer.lower(parsed.program);const auto generated=b.generate(lowered.program).cpp;return generated.find("sqlite3")==std::string::npos&&generated.find("curl/")==std::string::npos&&generated.find("openssl/")==std::string::npos&&generated.find("class strut_tcp_socket")==std::string::npos&&generated.find("class strut_process")==std::string::npos;};
req(bytes_minimal("bytes value := [0, 255];"),"basic bytes use minimal runtime");
req(bytes_minimal("bytes value := [0, 255]; value[0] = 1;"),"bytes indexing uses minimal runtime");
req(bytes_minimal("bytes value := [0, 255]; bytes part := value.slice(0, 1);"),"bytes slicing uses minimal runtime");
req(bytes_minimal("bytes value := [0, 255]; string text := value.to_string();"),"bytes to_string uses minimal runtime");
req(bytes_minimal("bytes value := bytes.from_string(\"x\");"),"bytes from_string uses minimal runtime");
req(bytes_minimal("bytes empty := bytes(); bytes large := bytes(65536);"),"bytes constructors use minimal runtime");
req(bytes_minimal("bytes left := [0]; bytes right := left; if (left != right) { return; }"),"bytes copy and equality use minimal runtime");
req(bytes_minimal("bytes empty := bytes(); if (!empty.empty()) { return; }"),"bytes empty check uses minimal runtime");
{ strut::SourceFile bs("bytes.p","function main() -> int { bytes empty := bytes(); if (!empty.empty()) { return 1; } bytes original := [0, 1, 127, 128, 255]; bytes copy := original; copy[0] = 9; if (original[0] != 0) { return 2; } bytes part := original.slice(1, 4); if (part.length() != 3) { return 3; } string raw := original.to_string(); bytes roundtrip := bytes.from_string(raw); if (roundtrip != original) { return 4; } bytes large := bytes(65536); if (large.length() != 65536) { return 5; } return 0; }");strut::Lexer bl(bs);auto bx=bl.lex();strut::Parser bp(bx.tokens);auto ba=bp.parse();req(ba.ok(),"bytes parse");strut::SemanticAnalyzer bsem;auto bsr=bsem.analyze(ba.program);req(bsr.ok(),"bytes sema");strut::IRLowerer blower;auto bir=blower.lower(ba.program);bir.program.source_path="bytes.p";auto bg=b.generate(bir.program);auto bo=temp.path()/"bytes";std::string be;req(b.compile(bir.program,bo,be),be.c_str());req(occurrences(bg.cpp,"class strut_bytes {")==1,"bytes implementation emitted once");req(std::system(("\""+native_executable(bo).string()+"\"").c_str())==0,"bytes native behavior");}
{ strut::SourceFile ts("text-stream.p","function main() -> void : StreamError { sstream stream; stream.write(\"text\"); stream.flush(); print(stream.str()); stream.close(); return; }");strut::Lexer tl(ts);auto tx=tl.lex();strut::Parser tp(tx.tokens);auto ta=tp.parse();req(ta.ok(),"text stream parse");strut::SemanticAnalyzer tsem;auto tsr=tsem.analyze(ta.program);req(tsr.ok(),"text stream sema");strut::IRLowerer tlower;auto tir=tlower.lower(ta.program);auto tg=b.generate(tir.program);req(tg.cpp.find("class strut_ostream")!=std::string::npos,"text stream runtime emitted");req(tg.cpp.find("curl/")==std::string::npos&&tg.cpp.find("openssl/")==std::string::npos&&tg.cpp.find("sqlite3")==std::string::npos&&tg.cpp.find("class strut_tcp_socket")==std::string::npos&&tg.cpp.find("class strut_process")==std::string::npos,"ordinary text streams exclude unrelated runtimes");}
{ strut::SourceFile ss("binary-streams.p","function main() -> int : StreamError { ofstream output := ofstream(\"strut-stream-test.bin\", true); output.write_bytes([]); bytes value := [0, 1, 127, 128, 255]; output.write_bytes(value); output.flush(); output.close(); output.close(); output.flush(); ifstream input := ifstream(\"strut-stream-test.bin\", true); if (input.eof()) { return 1; } bytes zero := input.read_bytes(0); if (!zero.empty() || input.eof()) { return 2; } bytes first := input.read_bytes(2); if (first.length() != 2 || first[0] != 0 || first[1] != 1 || input.eof()) { return 3; } bytes rest := input.read_all_bytes(3); if (rest.length() != 3 || rest[2] != 255 || !input.eof()) { return 4; } if (!input.read_bytes(1).empty()) { return 5; } input.close(); input.close(); return 0; }");strut::Lexer sl(ss);auto sx=sl.lex();strut::Parser sp(sx.tokens);auto sa=sp.parse();req(sa.ok(),"binary stream parse");strut::SemanticAnalyzer ssem;auto ssr=ssem.analyze(sa.program);req(ssr.ok(),"binary stream sema");strut::IRLowerer slower;auto sir=slower.lower(sa.program);sir.program.source_path="binary-streams.p";auto sg=b.generate(sir.program);req(occurrences(sg.cpp,"class strut_istream {")==1&&occurrences(sg.cpp,"class strut_ostream {")==1,"stream contracts emitted once");req(sg.cpp.find("curl/")==std::string::npos&&sg.cpp.find("openssl/")==std::string::npos&&sg.cpp.find("sqlite3")==std::string::npos&&sg.cpp.find("class strut_tcp_socket")==std::string::npos&&sg.cpp.find("class strut_process")==std::string::npos,"binary file streams exclude unrelated runtimes");auto so=temp.path()/"binary-streams";std::string se;req(b.compile(sir.program,so,se),se.c_str());req(std::system(("\""+native_executable(so).string()+"\"").c_str())==0,"binary file stream behavior");std::filesystem::remove("strut-stream-test.bin");}
{ strut::SourceFile fs("empty-bytes-file.p","include <filesystem>; function main() -> void : FilesystemError { write_file(\"empty-bytes.bin\", []); return; }");strut::Lexer fl(fs);auto fx=fl.lex();strut::Parser fp(fx.tokens);auto fa=fp.parse();req(fa.ok(),"empty bytes file parse");strut::SemanticAnalyzer fsem;auto fsr=fsem.analyze(fa.program);req(fsr.ok(),"empty bytes file sema");strut::IRLowerer flower;auto fir=flower.lower(fa.program);fir.program.standard_modules={"filesystem"};fir.program.source_path="empty-bytes-file.p";std::string fe;req(b.compile(fir.program,temp.path()/"empty-bytes-file",fe),fe.c_str());}
{ strut::SourceFile cs("cancellation.p","function detached_token() -> cancellation_token { cancellation_source local; return local.token(); } function main() -> int : (CancellationError, ThreadError) { cancellation_source source; cancellation_source source_copy := source; cancellation_token token := source.token(); cancellation_token token_copy := token; if (token.cancelled()) { return 1; } cancellation_token detached := detached_token(); if (detached.cancelled()) { return 2; } channel<bool> observed; worker := thread(() => { token_copy.wait(); observed.send(token_copy.cancelled()); }); source_copy.cancel(); source.cancel(); bool? result := observed.receive(); worker.join(); if (!(result ?? false) || !token.cancelled()) { return 3; } try { token.throw_if_cancelled(); } catch (CancellationError caught) { return 0; } return 4; }");strut::Lexer cl(cs);auto cx=cl.lex();strut::Parser cp(cx.tokens);auto ca=cp.parse();req(ca.ok(),"cancellation parse");strut::SemanticAnalyzer csem;auto csr=csem.analyze(ca.program);req(csr.ok(),"cancellation sema");strut::IRLowerer clower;auto cir=clower.lower(ca.program);cir.program.source_path="cancellation.p";auto cg=b.generate(cir.program);req(occurrences(cg.cpp,"class strut_cancellation_source {")==1,"cancellation implementation emitted once");auto co=temp.path()/"cancellation";std::string ce;req(b.compile(cir.program,co,ce),ce.c_str());req(std::system(("\""+native_executable(co).string()+"\"").c_str())==0,"cancellation native behavior");req(g.cpp.find("strut_cancellation_source")==std::string::npos,"hello omits cancellation runtime");}
{ strut::SourceFile cs("cancellation-slice.p","function main() -> int { cancellation_source source; cancellation_token token := source.token(); source.cancel(); if (token.cancelled()) { return 0; } return 1; }");strut::Lexer cl(cs);auto cx=cl.lex();strut::Parser cp(cx.tokens);auto ca=cp.parse();req(ca.ok(),"cancellation slice parse");strut::SemanticAnalyzer csem;auto csr=csem.analyze(ca.program);req(csr.ok(),"cancellation slice sema");strut::IRLowerer clower;auto cir=clower.lower(ca.program);cir.program.source_path="cancellation-slice.p";auto cg=b.generate(cir.program);req(cg.cpp.find("curl/")==std::string::npos&&cg.cpp.find("openssl/")==std::string::npos&&cg.cpp.find("sqlite3")==std::string::npos&&cg.cpp.find("class strut_tcp_socket")==std::string::npos&&cg.cpp.find("class strut_process")==std::string::npos,"cancellation-only runtime excludes unrelated subsystems");std::string ce;req(b.compile(cir.program,temp.path()/"cancellation-slice",ce),ce.c_str());}
return 0;}
