#include <cstdlib>
#include <filesystem>
#include <iostream>
#include "strut/codegen.h"
#include "strut/ir.h"
#include "strut/lexer.h"
#include "strut/parser.h"
#include "strut/sema.h"
#include "strut/source.h"
#include "temp_directory.h"
namespace {
void req(bool x,const char*m){if(!x){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);}}
std::filesystem::path native_executable(std::filesystem::path value) {
#ifdef _WIN32
 value += ".exe";
#endif
 return value;
}
}
int main(){TestTempDirectory temp("strut-codegen-test");strut::SourceFile s("hello.p","function add(int a, int b) -> int { return a + b; } function main() -> void { x := add(2,3); print(\"hello \" , x); return; }"); strut::Lexer l(s);auto lx=l.lex();strut::Parser p(lx.tokens);auto a=p.parse();req(a.ok(),"parse");strut::SemanticAnalyzer sem;auto sr=sem.analyze(a.program);req(sr.ok(),"sema");strut::IRLowerer lower;auto ir=lower.lower(a.program);ir.program.source_path="hello.p";strut::CppBackend b;auto g=b.generate(ir.program);req(g.cpp.find("strut_print")!=std::string::npos,"print generated");req(g.cpp.find("#line 1 \"hello.p\"")!=std::string::npos,"source line mapping generated");auto out=temp.path()/"program";std::string err;req(b.compile(ir.program,out,err),err.c_str());const auto native_out=native_executable(out);req(std::filesystem::exists(native_out),"native executable");
{ strut::SourceFile ms("minimal.p","function main() -> void { int x := 1; print(x); return; }"); strut::Lexer ml(ms); auto mx=ml.lex(); strut::Parser mp(mx.tokens); auto ma=mp.parse(); req(ma.ok(),"minimal parse"); strut::SemanticAnalyzer msem; auto msr=msem.analyze(ma.program); req(msr.ok(),"minimal sema"); strut::IRLowerer mlower; auto mir=mlower.lower(ma.program); auto mg=b.generate(mir.program); req(mg.cpp.find("json.h")==std::string::npos,"minimal runtime omits JSONIC"); req(mg.cpp.size()<5000,"minimal runtime remains compact"); }
{ strut::SourceFile vs("vec.p","function main() -> void { int[] values := []; values.push(1); print(values.length); return; }"); strut::Lexer vl(vs); auto vx=vl.lex(); strut::Parser vp(vx.tokens); auto va=vp.parse(); req(va.ok(),"vector parse"); strut::SemanticAnalyzer vsem; auto vsr=vsem.analyze(va.program); req(vsr.ok(),"vector sema"); strut::IRLowerer vlower; auto vir=vlower.lower(va.program); auto vg=b.generate(vir.program); req(vg.cpp.find("#include <vector>")!=std::string::npos,"vector runtime includes vector"); req(vg.cpp.find("#include <array>")==std::string::npos,"dynamic vector omits array header"); req(vg.cpp.find("#include <optional>")==std::string::npos,"non-nullable vector omits optional header"); req(vg.cpp.find("#include <type_traits>")==std::string::npos,"simple vector omits type-traits header"); }
{ strut::SourceFile maps("map.p","function main() -> void { int[] values := [1,2]; doubled := values.map((int x) => x * 2); print(doubled.length); return; }"); strut::Lexer ml2(maps); auto mx2=ml2.lex(); strut::Parser mp2(mx2.tokens); auto ma2=mp2.parse(); req(ma2.ok(),"map parse"); strut::SemanticAnalyzer msem2; auto msr2=msem2.analyze(ma2.program); req(msr2.ok(),"map sema"); strut::IRLowerer mlower2; auto mir2=mlower2.lower(ma2.program); auto mg2=b.generate(mir2.program); req(mg2.cpp.find("#include <vector>")!=std::string::npos,"map runtime includes vector"); req(mg2.cpp.find("#include <type_traits>")!=std::string::npos,"map runtime includes type traits"); req(mg2.cpp.find("#include <optional>")==std::string::npos,"map without nullable/find omits optional header"); }
{ strut::SourceFile cs("containers.p","function main() -> void { vector<int> v := [1,2]; map<int,int> m := [1:2]; ordered_map<int,int> om; set<int> s := [1,2]; ordered_set<int> os; queue<int> q; stack<int> st; deque<int> dq; list<int> li; priority_queue<int> pq; priority_queue<int,min> minpq; s.add(3); print(s.contains(3)); m.insert(2,3); return; }"); strut::Lexer cl(cs); auto cx=cl.lex(); strut::Parser cp(cx.tokens); auto ca=cp.parse(); req(ca.ok(),"containers parse"); strut::SemanticAnalyzer csem; auto csr=csem.analyze(ca.program); req(csr.ok(),"containers sema"); strut::IRLowerer clower; auto cir=clower.lower(ca.program); auto cg=b.generate(cir.program); req(cg.cpp.find("#include <unordered_map>")!=std::string::npos,"hash map includes unordered_map"); req(cg.cpp.find("#include <map>")!=std::string::npos,"ordered map includes map"); req(cg.cpp.find("#include <unordered_set>")!=std::string::npos,"hash set includes unordered_set"); req(cg.cpp.find("#include <set>")!=std::string::npos,"ordered set includes set"); req(cg.cpp.find("#include <queue>")!=std::string::npos,"queue/priority queue includes queue"); req(cg.cpp.find("#include <stack>")!=std::string::npos,"stack includes stack"); req(cg.cpp.find("#include <deque>")!=std::string::npos,"deque includes deque"); req(cg.cpp.find("#include <list>")!=std::string::npos,"list includes list"); req(cg.cpp.find("json.h")==std::string::npos,"numeric collections keep minimal runtime"); auto co=temp.path()/"collections"; std::string ce; cir.program.source_path="containers.p"; req(b.compile(cir.program,co,ce),ce.c_str()); }
{ strut::SourceFile pqs("pq.p","function main() -> void { priority_queue<int> q; q.push(1); print(q.top()); return; }"); strut::Lexer pql(pqs); auto pqx=pql.lex(); strut::Parser pqp(pqx.tokens); auto pqa=pqp.parse(); req(pqa.ok(),"priority queue parse"); strut::SemanticAnalyzer pqsem; auto pqsr=pqsem.analyze(pqa.program); req(pqsr.ok(),"priority queue sema"); strut::IRLowerer pqlower; auto pqir=pqlower.lower(pqa.program); auto pqg=b.generate(pqir.program); req(pqg.cpp.find("#include <queue>")!=std::string::npos,"priority queue includes queue"); req(pqg.cpp.find("#include <vector>")==std::string::npos,"max priority queue avoids explicit vector header"); req(pqg.cpp.find("#include <functional>")==std::string::npos,"max priority queue avoids comparator header"); }
{ strut::SourceFile hcs("http-client.p","function main() -> void : HttpError { response := http_get(\"http://127.0.0.1:9/\"); print(response.status); return; }"); strut::Lexer hcl(hcs); auto hcx=hcl.lex(); strut::Parser hcp(hcx.tokens); auto hca=hcp.parse(); req(hca.ok(),"http client parse"); strut::SemanticAnalyzer hcsem; auto hcsr=hcsem.analyze(hca.program); req(hcsr.ok(),"http client sema"); strut::IRLowerer hclower; auto hcir=hclower.lower(hca.program); auto hcg=b.generate(hcir.program); req(hcg.cpp.find("#define STRUT_USE_CURL 1")!=std::string::npos,"sync HTTP client enables curl"); req(hcg.cpp.find("strut_http_server")==std::string::npos,"sync HTTP client omits server runtime"); req(hcg.cpp.find("strut_executor")==std::string::npos,"sync HTTP client omits async executor"); req(hcg.cpp.size()<18000,"sync HTTP client runtime remains sliced"); }
{ strut::SourceFile hjs("http-json.p","function main() -> void : HttpError { body := http_get_json(\"https://example.com\"); print(body[\"name\"]); return; }");strut::Lexer hjl(hjs);auto hjx=hjl.lex();strut::Parser hjp(hjx.tokens);auto hja=hjp.parse();req(hja.ok(),"http JSON parse");strut::SemanticAnalyzer hjsem;auto hjsr=hjsem.analyze(hja.program);req(hjsr.ok(),"http JSON sema");strut::IRLowerer hjlower;auto hjir=hjlower.lower(hja.program);auto hjg=b.generate(hjir.program);req(hjg.cpp.find("json::Document body = http_get_json")!=std::string::npos&&hjg.cpp.find("strut_print(body[\"name\"])")!=std::string::npos,"HTTP JSON indexes as JSON rather than native container");}
{ strut::SourceFile gis("generic-array.p","function identity[T](T value) -> T { return value; } function main() -> void { int[] values := identity([1,2,3]); print(values.length); return; }");strut::Lexer gil(gis);auto gix=gil.lex();strut::Parser gip(gix.tokens);auto gia=gip.parse();req(gia.ok(),"generic array parse");strut::SemanticAnalyzer gisem;auto gisr=gisem.analyze(gia.program);req(gisr.ok(),"generic array sema");strut::IRLowerer gilower;auto giir=gilower.lower(gia.program);auto gig=b.generate(giir.program);req(gig.cpp.find("identity(std::vector<std::int32_t>{1,2,3})")!=std::string::npos,"array literal call argument carries concrete vector type");}
{ strut::IRProgram native;auto call=std::make_unique<strut::IRStmt>();call->value=std::make_unique<strut::IRExpr>();call->value->kind=strut::IRExpr::Kind::identifier;call->value->text="http_get";native.statements.push_back(std::move(call));const auto guidance=strut::classify_native_failure(native,"linking");req(guidance.find("native linking failed")!=std::string::npos&&guidance.find("required native library curl")!=std::string::npos&&guidance.find("secondary detail")!=std::string::npos,"native dependency failures are actionable");}
{ strut::SourceFile ps("ptr.p","function read(int* p) -> int { return *p; } function replace(int* p) -> void { p = new(2); return; }"); strut::Lexer pl(ps); auto px=pl.lex(); strut::Parser pp(px.tokens); auto pa=pp.parse(); req(pa.ok(),"ptr parse"); strut::SemanticAnalyzer psem; auto psr=psem.analyze(pa.program); req(psr.ok(),"ptr sema"); strut::IRLowerer lower2; auto pir=lower2.lower(pa.program); auto pg=b.generate(pir.program); req(pg.cpp.find("const std::shared_ptr<std::int32_t>& p")!=std::string::npos,"read-only ptr parameter borrowed"); req(pg.cpp.find("std::shared_ptr<std::int32_t> p")!=std::string::npos,"assigned ptr parameter remains owning value"); req(pg.cpp.find("#include <optional>")==std::string::npos,"non-nullable pointer runtime omits optional header"); }
{ strut::SourceFile fs("fs.p","function main() -> void : FilesystemError { bool x := exists(\".\"); print(x); return; }"); strut::Lexer fl(fs); auto fx=fl.lex(); strut::Parser fp(fx.tokens); auto fa=fp.parse(); req(fa.ok(),"filesystem parse"); strut::SemanticAnalyzer fsem; auto fsr=fsem.analyze(fa.program); req(fsr.ok(),"filesystem sema"); strut::IRLowerer flower; auto fir=flower.lower(fa.program); fir.program.standard_modules={"filesystem"}; auto fg=b.generate(fir.program); req(fg.cpp.find("json.h")==std::string::npos,"filesystem runtime omits JSONIC"); req(fg.cpp.size()<25000,"filesystem runtime remains sliced"); }
{ strut::SourceFile hs("http.p","function main() -> void : NetworkError { http_server app := http_server(); app.get(\"/\", (http_request req) => { return http_text(\"ok\"); }); return; }"); strut::Lexer hl(hs); auto hx=hl.lex(); strut::Parser hp(hx.tokens); auto ha=hp.parse(); req(ha.ok(),"http parse"); strut::SemanticAnalyzer hsem; auto hsr=hsem.analyze(ha.program); req(hsr.ok(),"http sema"); strut::IRLowerer hlower; auto hir=hlower.lower(ha.program); auto hg=b.generate(hir.program); req(hg.cpp.find("json.h")==std::string::npos,"server-only HTTP runtime omits JSONIC"); req(hg.cpp.find("curl/curl.h")==std::string::npos,"server-only HTTP runtime omits curl"); req(hg.cpp.size()<25000,"server-only HTTP runtime remains sliced"); }
{ strut::SourceFile ls("http-lifecycle.p","function main() -> void : NetworkError { app := http_server(); app.timeouts(1000, 1000, 1000, 500); app.limits(1024, 4096, 20, 8); if (app.running()) { app.stop(); } return; }");strut::Lexer ll(ls);auto lx=ll.lex();strut::Parser lp(lx.tokens);auto la=lp.parse();req(la.ok(),"HTTP lifecycle parse");strut::SemanticAnalyzer lsem;auto lsr=lsem.analyze(la.program);req(lsr.ok(),"HTTP lifecycle sema");strut::IRLowerer llower;auto lir=llower.lower(la.program);auto lg=b.generate(lir.program);req(lg.cpp.find("void stop() const")!=std::string::npos&&lg.cpp.find("Payload Too Large")!=std::string::npos,"HTTP lifecycle runtime emitted");}
{ strut::SourceFile fsp("fs-path.p","function main() -> void : FilesystemError { print(filename(\"a/b.txt\")); return; }"); strut::Lexer fpl(fsp); auto fpx=fpl.lex(); strut::Parser fpp(fpx.tokens); auto fpa=fpp.parse(); req(fpa.ok(),"filesystem path parse"); strut::SemanticAnalyzer fpsem; auto fpsr=fpsem.analyze(fpa.program); req(fpsr.ok(),"filesystem path sema"); strut::IRLowerer fplower; auto fpir=fplower.lower(fpa.program); fpir.program.standard_modules={"filesystem"}; auto fpg=b.generate(fpir.program); req(fpg.cpp.find("strut_fs_wildcard_match")==std::string::npos,"path-only filesystem omits wildcard machinery"); req(fpg.cpp.find("strut_fs_read_file")==std::string::npos,"path-only filesystem omits file IO"); }
{ strut::SourceFile as("async.p","async function twice(int x) -> int { return x * 2; } function main() -> void { pending := twice(2); print(await pending); return; }"); strut::Lexer al(as); auto ax=al.lex(); strut::Parser ap(ax.tokens); auto aa=ap.parse(); req(aa.ok(),"async parse"); strut::SemanticAnalyzer asem; auto asr=asem.analyze(aa.program); req(asr.ok(),"async sema"); strut::IRLowerer alower; auto air=alower.lower(aa.program); auto ag=b.generate(air.program); req(ag.cpp.find("json.h")==std::string::npos,"async runtime omits JSONIC"); req(ag.cpp.size()<12000,"async runtime remains sliced"); }
{ strut::SourceFile das("direct-async.p","async function answer() -> int { return 42; } function main() -> int { print(await answer()); return 0; }");strut::Lexer dal(das);auto dax=dal.lex();strut::Parser dap(dax.tokens);auto daa=dap.parse();req(daa.ok(),"direct await parse");strut::SemanticAnalyzer dasem;auto dasr=dasem.analyze(daa.program);req(dasr.ok(),"direct await sema");strut::IRLowerer dalower;auto dair=dalower.lower(daa.program);dair.program.source_path="direct-async.p";auto dao=temp.path()/"direct-async";std::string dae;req(b.compile(dair.program,dao,dae),dae.c_str());}
{ strut::SourceFile ns("nested-function.p","function main() -> void { vector<function<(int)->int>> callbacks := []; return; }");strut::Lexer nl(ns);auto nx=nl.lex();strut::Parser np(nx.tokens);auto na=np.parse();req(na.ok(),"nested function type parse");strut::SemanticAnalyzer nsem;auto nsr=nsem.analyze(na.program);req(nsr.ok(),"nested function type sema");strut::IRLowerer nlower;auto nir=nlower.lower(na.program);auto ng=b.generate(nir.program);req(ng.cpp.find("std::vector<std::function<std::int32_t(std::int32_t)>> callbacks")!=std::string::npos,"nested function TypeId lowers structurally");}
return 0;}
