#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include "strut/lsp.h"
#include "strut/package.h"
#include "temp_directory.h"

namespace {
void request(std::stringstream& in,const std::string& body){in<<"Content-Length: "<<body.size()<<"\r\n\r\n"<<body;}
void require(bool value,const char* message,const std::string& output){if(!value){std::cerr<<"FAIL: "<<message<<'\n'<<output;std::exit(1);}}
std::string quoted(std::string value){std::string out="\"";for(char c:value){if(c=='\\'||c=='\"'){out+='\\';out+=c;}else if(c=='\n')out+="\\n";else if(c=='\r')out+="\\r";else if(c=='\t')out+="\\t";else out+=c;}return out+'\"';}
}

int main(){
    TestTempDirectory temp("strut-lsp-project");const auto root=temp.path();
    const auto home=root/"package-home";
#ifdef _WIN32
    _putenv_s("STRUT_HOME",home.string().c_str());
#else
    setenv("STRUT_HOME",home.string().c_str(),1);
#endif
    const auto child_source=root/"child-source";std::filesystem::create_directories(child_source);std::ofstream(child_source/"strut.json")<<R"({"name":"child-lsp","version":"1.0.0","entry":"main.p"})";std::ofstream(child_source/"main.p")<<"function transitive_hidden() -> int { return 3; }\nexport transitive_hidden;\n";std::filesystem::path child_cached;strut::PackageManifest child_package;std::string package_error;require(strut::cache_local_package(child_source,child_cached,child_package,package_error),"cache child LSP package",package_error);std::filesystem::remove_all(child_source);
    const auto package_source=root/"package-source";std::filesystem::create_directories(package_source);std::ofstream(package_source/"strut.json")<<R"({"name":"local","version":"1.0.0","entry":"main.p","dependencies":{"child-lsp":"1.0.0"}})";std::ofstream(package_source/"main.p")<<"include \"public.h\";\ninclude <child-lsp>;\nexport package_facade;\nexport alias_facade;\nexport package_symbol;\nexport takes_string;\nexport Thing;\nexport PublicThing;\n";std::ofstream(package_source/"public.h")<<"struct PackageCarrier { int value; function facade_member() -> int { return value; } }\npackage_facade := PackageCarrier { value: 7 };\nstruct AliasCarrier { function alias_member() -> int { return 8; } }\ntype DeepCarrierAlias := AliasCarrier;\ntype CarrierAlias := DeepCarrierAlias;\nCarrierAlias alias_facade := AliasCarrier {};\nstruct PublicThing { int public_field; function public_member() -> int { return public_field; } }\nfunction package_symbol(string value) -> int { return transitive_hidden(); }\nfunction takes_string(string value) -> int { return 1; }\nfunction Thing() -> int { return 1; }\nfunction package_private() -> int { return 1; }\n";std::ofstream(package_source/"unreachable.p")<<"function unreachable_hidden() -> int { return 0; }\n";std::filesystem::path cached;strut::PackageManifest package;require(strut::cache_local_package(package_source,cached,package,package_error),"cache LSP package",package_error);std::filesystem::remove_all(package_source);
    strut::PackageManifest project;project.name="lsp-test";project.version="0.1.0";project.dependencies["local"]="1.0.0";require(strut::write_package_manifest_file(root/"strut.json",project,package_error),"write LSP manifest",package_error);require(strut::write_lockfile(root,project,package_error),"write LSP lock",package_error);
    std::ofstream(root/"helper.p")<<"function helper(string value) -> int { return 1; }\n";
    const auto uri="file://"+(root/"main.p").generic_string();
    const std::string source="include <local>;\nfunction main() -> int : HttpError {\n  http_response response := http_get(\"https://example.test\");\n  response.;\n  result := exec(\"echo\", [\"ok\"]);\n  helper(\"x\");\n  package_symbol(\"x\");\n  package_facade.;\n  alias_facade.;\n  PublicThing public_thing;\n  public_thing.;\n  return 0;\n}\n";
    std::stringstream in,out,err;
    request(in,R"({"jsonrpc":"2.0","id":1,"method":"initialize","params":{}})");
    request(in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(source)+"}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":3,\"character\":11}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"textDocument/signatureHelp\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":4,\"character\":31}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":4,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":31}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":5,\"method\":\"textDocument/definition\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":5,\"character\":4}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":6,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":1,\"character\":0}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":7,\"method\":\"textDocument/documentSymbol\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":10,\"method\":\"textDocument/definition\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":6,\"character\":5}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":12,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":6,\"character\":5}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":13,\"method\":\"textDocument/signatureHelp\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":6,\"character\":20}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":30,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":7,\"character\":17}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":37,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":8,\"character\":15}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":31,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":10,\"character\":15}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didChange\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"contentChanges\":[{\"text\":\"function main( {\\n  pri\\n\"}]}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"id\":8,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":1,\"character\":5}}}");
    request(in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didClose\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"}}}");
    request(in,R"({"jsonrpc":"2.0","id":9,"method":"shutdown","params":{}})");request(in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");
    require(strut::run_lsp(in,out,err)==0,"server exit",out.str()+err.str());const auto s=out.str();
    require(s.find("signatureHelpProvider")!=std::string::npos,"signature capability",s);
    require(s.find("documentSymbolProvider")!=std::string::npos,"document symbol capability",s);
    require(s.find("json() -> json")!=std::string::npos,"TypeId method completion",s);
    require(s.find("\"label\": \"status\"")!=std::string::npos&&s.find("int_32 status")!=std::string::npos,"registry field completion",s);
    require(s.find("exec(string program, string[] args, json options?) -> exec_result")!=std::string::npos,"signature help",s);
    require(s.find("\"activeParameter\": 1")!=std::string::npos,"active argument",s);
    require(s.find("Checked errors: HttpError")!=std::string::npos,"checked error hover",s);
    require(s.find("helper.p")!=std::string::npos,"project definition",s);
    require(s.find(cached.generic_string()+"/public.h")!=std::string::npos,"package definition in entry include closure",s);
    require(s.find("\"label\": \"package_symbol\"")!=std::string::npos,"package completion",s);
    require(s.find("\"label\": \"package_facade\"")!=std::string::npos,"exported package facade completion",s);
    require(s.find("opaque package_facade")!=std::string::npos&&s.find("PackageCarrier package_facade")==std::string::npos,"private facade carrier hidden",s);
    require(s.find("opaque alias_facade")!=std::string::npos&&s.find("CarrierAlias alias_facade")==std::string::npos,"private alias facade carrier hidden",s);
    require(s.find("\"label\": \"package_private\"")==std::string::npos,"private package symbol excluded from completion",s);
    require(s.find("\"label\": \"facade_member\"")!=std::string::npos,"private-carrier facade member completion",s);
    require(s.find("\"label\": \"alias_member\"")!=std::string::npos,"alias-backed private facade member completion",s);
    require(s.find("\"label\": \"public_member\"")!=std::string::npos&&s.find("\"label\": \"public_field\"")!=std::string::npos,"exported struct member completion",s);
    require(s.find("transitive_hidden")==std::string::npos,"transitive package symbol omitted",s);
    require(s.find("unreachable_hidden")==std::string::npos,"unreachable package file omitted",s);
    require(s.find("function package_symbol(string value) -> int")!=std::string::npos,"package hover and signature",s);
    require(s.find("additionalTextEdits")!=std::string::npos,"module import edit",s);
    require(s.find("\"label\": \"sha256\"")!=std::string::npos&&s.find("Compute a raw 32-byte SHA-256 digest.")!=std::string::npos,"crypto registry completion",s);
    require(s.find("\"label\": \"base64_decode\"")!=std::string::npos&&s.find("Decode strict canonical padded RFC 4648 Base64.")!=std::string::npos,"encoding registry completion",s);
    require(s.find("\"code\":")!=std::string::npos,"structured diagnostics",s);
    require(s.find("\"label\": \"print\"")!=std::string::npos,"incomplete source recovery",s);
    require(s.find("\"diagnostics\": []")!=std::string::npos,"didClose clears diagnostics",s);
    const std::string valid_package_source="include <local>;\nfunction main() -> int { return package_symbol(\"x\"); }\n";std::stringstream valid_in,valid_out,valid_err;request(valid_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(valid_package_source)+"}}}");request(valid_in,R"({"jsonrpc":"2.0","id":32,"method":"shutdown","params":{}})");request(valid_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(valid_in,valid_out,valid_err)==0,"valid package diagnostics LSP exit",valid_out.str()+valid_err.str());require(valid_out.str().find("\"diagnostics\": []")!=std::string::npos,"valid exported package use has no false diagnostics",valid_out.str());
    const std::string absent_package_source="function main() -> int { return package_symbol(\"x\"); }\n";std::stringstream absent_in,absent_out,absent_err;request(absent_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(absent_package_source)+"}}}");request(absent_in,R"({"jsonrpc":"2.0","id":33,"method":"shutdown","params":{}})");request(absent_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(absent_in,absent_out,absent_err)==0,"absent package include LSP exit",absent_out.str()+absent_err.str());require(absent_out.str().find("unknown callable 'package_symbol'")!=std::string::npos,"unimported package API remains unknown",absent_out.str());
    const std::string wrong_arity_source="include <local>;\nfunction main() -> int { return package_symbol(); }\n";std::stringstream arity_in,arity_out,arity_err;request(arity_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(wrong_arity_source)+"}}}");request(arity_in,R"({"jsonrpc":"2.0","id":34,"method":"shutdown","params":{}})");request(arity_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(arity_in,arity_out,arity_err)==0,"package wrong arity LSP exit",arity_out.str()+arity_err.str());require(arity_out.str().find("call to 'package_symbol' expects 1 argument(s), found 0")!=std::string::npos,"wrong-arity package call remains diagnostic",arity_out.str());
    const std::string wrong_type_source="include <local>;\nfunction main() -> int { return takes_string(1); }\n";std::stringstream type_in,type_out,type_err;request(type_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(wrong_type_source)+"}}}");request(type_in,R"({"jsonrpc":"2.0","id":35,"method":"shutdown","params":{}})");request(type_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(type_in,type_out,type_err)==0,"package wrong literal type LSP exit",type_out.str()+type_err.str());require(type_out.str().find("argument 1 to 'takes_string' expects string, found int_32")!=std::string::npos,"wrong-type package call remains diagnostic",type_out.str());
    const std::string wrong_namespace_source="include <local>;\nfunction main() -> void { Thing value; return; }\n";std::stringstream namespace_in,namespace_out,namespace_err;request(namespace_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(wrong_namespace_source)+"}}}");request(namespace_in,R"({"jsonrpc":"2.0","id":38,"method":"shutdown","params":{}})");request(namespace_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(namespace_in,namespace_out,namespace_err)==0,"package namespace diagnostic LSP exit",namespace_out.str()+namespace_err.str());require(namespace_out.str().find("unknown type 'Thing'")!=std::string::npos,"exported function does not suppress unknown type diagnostic",namespace_out.str());
    std::ofstream(root/"helper.p")<<"include <local>;\n";const std::string indirect_source="include \"helper.p\";\nfunction main() -> int { return package_symbol(\"x\"); }\n";std::stringstream indirect_in,indirect_out,indirect_err;request(indirect_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(indirect_source)+"}}}");request(indirect_in,R"({"jsonrpc":"2.0","id":36,"method":"shutdown","params":{}})");request(indirect_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(indirect_in,indirect_out,indirect_err)==0,"quoted include package discovery LSP exit",indirect_out.str()+indirect_err.str());require(indirect_out.str().find("\"diagnostics\": []")!=std::string::npos,"package API discovered through quoted include closure",indirect_out.str());
    std::filesystem::remove_all(cached);std::stringstream missing_in,missing_out,missing_err;request(missing_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(source)+"}}}");request(missing_in,R"({"jsonrpc":"2.0","id":11,"method":"shutdown","params":{}})");request(missing_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(missing_in,missing_out,missing_err)==0,"missing package server exit",missing_out.str()+missing_err.str());require(missing_out.str().find("package `local` is locked but not present in the verified cache")!=std::string::npos,"missing package diagnostic",missing_out.str());require(missing_out.str().find("run `strut install`")!=std::string::npos,"missing package help",missing_out.str());std::filesystem::remove_all(child_cached);
    const std::string server_source="function main() -> void : NetworkError {\n  app := http_server();\n  app.;\n  return;\n}\n";std::stringstream server_in,server_out,server_err;request(server_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(server_source)+"}}}");request(server_in,"{\"jsonrpc\":\"2.0\",\"id\":14,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":6}}}");request(server_in,R"({"jsonrpc":"2.0","id":15,"method":"shutdown","params":{}})");request(server_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(server_in,server_out,server_err)==0,"HTTP lifecycle LSP exit",server_out.str()+server_err.str());require(server_out.str().find("\"label\": \"stop\"")!=std::string::npos&&server_out.str().find("\"label\": \"running\"")!=std::string::npos&&server_out.str().find("\"label\": \"listen_tls\"")!=std::string::npos&&server_out.str().find("\"label\": \"get_async\"")!=std::string::npos&&server_out.str().find("\"label\": \"static\"")!=std::string::npos,"HTTP schema completion",server_out.str());
    const std::string stream_source="function main() -> void : StreamError {\n  ifstream input;\n  input.;\n  return;\n}\n";std::stringstream stream_in,stream_out,stream_err;request(stream_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(stream_source)+"}}}");request(stream_in,"{\"jsonrpc\":\"2.0\",\"id\":21,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":8}}}");request(stream_in,R"({"jsonrpc":"2.0","id":22,"method":"shutdown","params":{}})");request(stream_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(stream_in,stream_out,stream_err)==0,"binary stream LSP exit",stream_out.str()+stream_err.str());require(stream_out.str().find("\"label\": \"read_bytes\"")!=std::string::npos&&stream_out.str().find("\"label\": \"read_all_bytes\"")!=std::string::npos&&stream_out.str().find("\"label\": \"eof\"")!=std::string::npos,"binary stream schema completion",stream_out.str());
    const std::string cancellation_source="function main() -> void : CancellationError {\n  cancellation_token token;\n  token.;\n  return;\n}\n";std::stringstream cancellation_in,cancellation_out,cancellation_err;request(cancellation_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(cancellation_source)+"}}}");request(cancellation_in,"{\"jsonrpc\":\"2.0\",\"id\":23,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":8}}}");request(cancellation_in,R"({"jsonrpc":"2.0","id":24,"method":"shutdown","params":{}})");request(cancellation_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(cancellation_in,cancellation_out,cancellation_err)==0,"cancellation LSP exit",cancellation_out.str()+cancellation_err.str());require(cancellation_out.str().find("\"label\": \"cancelled\"")!=std::string::npos&&cancellation_out.str().find("\"label\": \"wait\"")!=std::string::npos&&cancellation_out.str().find("\"label\": \"throw_if_cancelled\"")!=std::string::npos,"cancellation schema completion",cancellation_out.str());
    const std::string error_source="error AppError { string message; int code; }\nfunction make() -> AppError { return AppError { message: \"bad\", code: 1 }; }\n";std::stringstream error_in,error_out,error_err;request(error_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(error_source)+"}}}");request(error_in,"{\"jsonrpc\":\"2.0\",\"id\":16,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":0,\"character\":8}}}");request(error_in,"{\"jsonrpc\":\"2.0\",\"id\":17,\"method\":\"textDocument/definition\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":1,\"character\":22}}}");request(error_in,"{\"jsonrpc\":\"2.0\",\"id\":18,\"method\":\"textDocument/documentSymbol\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"}}}");request(error_in,"{\"jsonrpc\":\"2.0\",\"id\":19,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":1,\"character\":27}}}");request(error_in,R"({"jsonrpc":"2.0","id":20,"method":"shutdown","params":{}})");request(error_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(error_in,error_out,error_err)==0,"custom error LSP exit",error_out.str()+error_err.str());const auto error_lsp=error_out.str();require(error_lsp.find("error AppError")!=std::string::npos,"custom error hover and symbol detail",error_lsp);require(error_lsp.find("\"label\": \"AppError\"")!=std::string::npos,"custom error type completion",error_lsp);require(error_lsp.find("\"uri\": "+quoted(uri))!=std::string::npos,"custom error definition",error_lsp);
    const std::string request_source="function inspect(http_request request) -> void {\n  request.;\n  token := request.cancellation;\n}\n";std::stringstream request_in,request_out,request_err;request(request_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(request_source)+"}}}");request(request_in,"{\"jsonrpc\":\"2.0\",\"id\":25,\"method\":\"textDocument/completion\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":1,\"character\":10}}}");request(request_in,"{\"jsonrpc\":\"2.0\",\"id\":26,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":24}}}");request(request_in,R"({"jsonrpc":"2.0","id":27,"method":"shutdown","params":{}})");request(request_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(request_in,request_out,request_err)==0,"request cancellation LSP exit",request_out.str()+request_err.str());require(request_out.str().find("cancellation_token cancellation")!=std::string::npos&&request_out.str().find("read-only cancellation_token cancellation")!=std::string::npos&&request_out.str().find("Read-only token cancelled when this request lifetime ends.")!=std::string::npos,"request cancellation completion and read-only hover",request_out.str());
    const std::string collision_source="struct Collision { cancellation_token cancellation; }\nfunction inspect(http_request request) -> void {\n  token := request.cancellation;\n}\n";std::stringstream collision_in,collision_out,collision_err;request(collision_in,"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+",\"text\":"+quoted(collision_source)+"}}}");request(collision_in,"{\"jsonrpc\":\"2.0\",\"id\":28,\"method\":\"textDocument/hover\",\"params\":{\"textDocument\":{\"uri\":"+quoted(uri)+"},\"position\":{\"line\":2,\"character\":24}}}");request(collision_in,R"({"jsonrpc":"2.0","id":29,"method":"shutdown","params":{}})");request(collision_in,R"({"jsonrpc":"2.0","method":"exit","params":{}})");require(strut::run_lsp(collision_in,collision_out,collision_err)==0,"request cancellation collision LSP exit",collision_out.str()+collision_err.str());require(collision_out.str().find("read-only cancellation_token cancellation")!=std::string::npos&&collision_out.str().find("Read-only token cancelled when this request lifetime ends.")!=std::string::npos,"receiver-aware request cancellation hover",collision_out.str());
    require(request_out.str().find("\"label\": \"query_values\"")!=std::string::npos&&request_out.str().find("\"label\": \"cookies\"")!=std::string::npos,"HTTP application helper completion",request_out.str());
    return 0;
}
