#include <algorithm>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <thread>
#include "strut/package.h"
#include "temp_directory.h"
namespace{
void req(bool ok,const char*m){if(!ok){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);}}
std::string read(const std::filesystem::path&p){std::ifstream f(p);return {std::istreambuf_iterator<char>(f),{}};}
std::string quote(const std::filesystem::path&p){return "\""+p.string()+"\"";}
std::filesystem::path cache_fixture(const std::filesystem::path&root,const std::string&directory,const std::string&manifest_text){
 const auto source=root/directory;std::filesystem::create_directories(source);std::ofstream(source/"strut.json")<<manifest_text;std::ofstream(source/"main.p")<<"function fixture() -> int { return 1; }\n";
 std::filesystem::path cached;strut::PackageManifest manifest;std::string error;req(strut::cache_local_package(source,cached,manifest,error),error.c_str());return cached;
}
}
int main(){
 req(strut::valid_package_name("http")&&!strut::valid_package_name("HTTP"),"package names");
 req(strut::valid_package_relative_path("src/main.p")&&!strut::valid_package_relative_path("../bad"),"package paths");
 req(strut::valid_version_requirement("1.2.3")&&strut::valid_version_requirement("^1.2.3")&&!strut::valid_version_requirement("latest"),"versions");
 std::string error;strut::PackageManifest manifest;
 req(strut::parse_package_manifest(R"({"name":"demo","version":"0.1.0","dependencies":{"http":"^0.2.0"}})",manifest,error),error.c_str());
 req(!strut::parse_package_manifest(R"({"name":"demo","version":"0.1.0","dependencies":{"../escape":"1.0.0"}})",manifest,error)&&error.find("package name")!=std::string::npos,"dependency traversal rejected");
 req(!strut::parse_package_manifest(R"({"name":"demo","version":"0.1.0","dependencies":{"bad":{"version":"1.0.0","git":"-dangerous","rev":"1111111111111111111111111111111111111111"}}})",manifest,error),"unsafe Git URL rejected");
 TestTempDirectory temp("strut-package-test");const auto root=temp.path(),home=root/"home";
#ifdef _WIN32
 _putenv_s("STRUT_HOME",home.string().c_str());
#else
 setenv("STRUT_HOME",home.string().c_str(),1);
#endif
 std::filesystem::create_directories(root/"empty");std::string checksum;req(strut::package_content_checksum(root/"empty",checksum,error),error.c_str());req(checksum=="sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","SHA-256");
 const auto local_root=root/"local";std::filesystem::create_directories(local_root);std::ofstream(local_root/"strut.json")<<R"({"name":"local","version":"1.2.3","entry":"main.p"})";std::ofstream(local_root/"main.p")<<"function answer() -> int { return 42; }\n";
 std::filesystem::path cached;strut::PackageManifest local;req(strut::cache_local_package(local_root,cached,local,error),error.c_str());req(cached.parent_path().filename()=="1.2.3"&&cached.filename().string().size()==64,"content address");
 std::filesystem::path hit;strut::PackageManifest hit_manifest;req(strut::cache_local_package(local_root,hit,hit_manifest,error)&&hit==cached,"cache hit");
 std::ofstream(cached/"main.p",std::ios::app)<<"corrupt";std::string corruption;req(!strut::resolve_cached_package("local","1.2.3",&corruption)&&corruption.find("checksum")!=std::string::npos,"corruption detection");req(strut::cache_local_package(local_root,cached,local,error),error.c_str());
 std::filesystem::remove_all(cached);std::filesystem::path ap,bp;strut::PackageManifest am,bm;std::string ae,be;bool ao=false,bo=false;std::thread a([&]{ao=strut::cache_local_package(local_root,ap,am,ae);}),b([&]{bo=strut::cache_local_package(local_root,bp,bm,be);});a.join();b.join();req(ao&&bo&&ap==bp,"concurrent promotion");
 strut::PackageManifest app;app.name="app";app.version="0.1.0";app.dependencies["local"]="^1.0.0";req(strut::write_lockfile(root,app,error),error.c_str());const auto first=read(root/"strut.lock.json");req(first.find(root.generic_string())==std::string::npos,"path-free lock");strut::PackageLock parsed;req(strut::parse_package_lock(first,parsed,error),error.c_str());req(strut::write_package_lock_file(root/"second.lock",parsed,error)&&read(root/"second.lock")==first,"stable round trip");
 cache_fixture(root,"shared-1",R"({"name":"shared","version":"1.2.0"})");
 cache_fixture(root,"shared-2",R"({"name":"shared","version":"2.0.0"})");
 cache_fixture(root,"alpha",R"({"name":"alpha","version":"1.0.0","dependencies":{"shared":"^1.0.0"}})");
 cache_fixture(root,"beta",R"({"name":"beta","version":"1.0.0","dependencies":{"shared":"~1.2.0"}})");
 strut::PackageManifest graph;graph.name="graph";graph.version="0.1.0";graph.dependencies["alpha"]="1.0.0";graph.dependencies["beta"]="1.0.0";req(strut::write_lockfile(root,graph,error),error.c_str());strut::PackageLock graph_lock;req(strut::load_package_lock_file(root/"strut.lock.json",graph_lock,error),error.c_str());
 std::size_t shared_count=0;for(const auto& package:graph_lock.packages){if(package.name=="shared"){++shared_count;req(package.version=="1.2.0"&&!package.direct,"shared version");}if(package.name=="alpha"||package.name=="beta")req(package.dependencies.at("shared")=="1.2.0","exact transitive edge");}req(graph_lock.packages.size()==3&&shared_count==1,"shared dependency deduplication");const auto deterministic=read(root/"strut.lock.json");req(strut::write_lockfile(root,graph,error)&&read(root/"strut.lock.json")==deterministic,"deterministic graph resolution");
 std::vector<std::string> graph_names;for(const auto& package:graph_lock.packages)graph_names.push_back(package.name);req(std::is_sorted(graph_names.begin(),graph_names.end()),"deterministic graph ordering");
 cache_fixture(root,"exact-common",R"({"name":"exact-common","version":"1.0.0"})");cache_fixture(root,"exact-a",R"({"name":"exact-a","version":"1.0.0","dependencies":{"exact-common":"1.0.0"}})");cache_fixture(root,"exact-b",R"({"name":"exact-b","version":"1.0.0","dependencies":{"exact-common":"1.0.0"}})");strut::PackageManifest exact;exact.name="exact";exact.version="0.1.0";exact.dependencies["exact-a"]="1.0.0";exact.dependencies["exact-b"]="1.0.0";req(strut::write_lockfile(root,exact,error),error.c_str());strut::PackageLock exact_lock;req(strut::load_package_lock_file(root/"strut.lock.json",exact_lock,error),error.c_str());std::size_t exact_common_count=0;for(const auto& package:exact_lock.packages)if(package.name=="exact-common")++exact_common_count;req(exact_common_count==1,"exact duplicate requirement");
 cache_fixture(root,"omega",R"({"name":"omega","version":"1.0.0","dependencies":{"shared":"2.0.0"}})");strut::PackageManifest conflict=graph;conflict.dependencies.erase("beta");conflict.dependencies["omega"]="1.0.0";req(!strut::write_lockfile(root,conflict,error)&&error.find("alpha")!=std::string::npos&&error.find("omega")!=std::string::npos&&error.find("^1.0.0")!=std::string::npos&&error.find("2.0.0")!=std::string::npos,"requirement conflict paths");
 cache_fixture(root,"cycle-a",R"({"name":"cycle-a","version":"1.0.0","dependencies":{"cycle-b":"1.0.0"}})");cache_fixture(root,"cycle-b",R"({"name":"cycle-b","version":"1.0.0","dependencies":{"cycle-a":"1.0.0"}})");strut::PackageManifest cyclic;cyclic.name="cyclic";cyclic.version="0.1.0";cyclic.dependencies["cycle-a"]="1.0.0";req(!strut::write_lockfile(root,cyclic,error)&&error.find("cycle-a -> cycle-b -> cycle-a")!=std::string::npos,"cycle path");
 cache_fixture(root,"self-cycle",R"({"name":"self-cycle","version":"1.0.0","dependencies":{"self-cycle":"1.0.0"}})");strut::PackageManifest self;self.name="self";self.version="0.1.0";self.dependencies["self-cycle"]="1.0.0";req(!strut::write_lockfile(root,self,error)&&error.find("self-cycle -> self-cycle")!=std::string::npos,"self cycle path");
 strut::PackageManifest source_conflict=graph;source_conflict.dependencies.erase("beta");source_conflict.dependencies["shared"]="^1.0.0";source_conflict.dependency_sources["shared"]={"git","https://example.invalid/one.git",std::string(40,'1')};cache_fixture(root,"alpha-source",R"({"name":"alpha-source","version":"1.0.0","dependencies":{"shared":{"version":"^1.0.0","git":"https://example.invalid/two.git","rev":"2222222222222222222222222222222222222222"}}})");source_conflict.dependencies.erase("alpha");source_conflict.dependencies["alpha-source"]="1.0.0";req(!strut::write_lockfile(root,source_conflict,error)&&error.find("source identity conflict")!=std::string::npos&&error.find("project 'graph'")!=std::string::npos&&error.find("package 'alpha-source'")!=std::string::npos,"source conflict paths");
 auto duplicate=parsed;duplicate.packages.push_back(duplicate.packages[0]);req(!strut::validate_package_lock(duplicate,nullptr,error)&&error.find("duplicate")!=std::string::npos,"duplicate rejection");auto cycle=parsed;cycle.packages[0].dependencies["local"]="1.2.3";req(!strut::validate_package_lock(cycle,nullptr,error)&&error.find("cyclic")!=std::string::npos,"cycle rejection");strut::PackageLock legacy;req(!strut::parse_package_lock(R"({"version":1,"dependencies":{}})",legacy,error),"legacy rejection");
 const auto remote=root/"remote";std::filesystem::create_directories(remote);std::ofstream(remote/"strut.json")<<R"({"name":"remote","version":"2.0.0","entry":"main.p"})";std::ofstream(remote/"main.p")<<"function value() -> int { return 7; }\n";
 req(std::system(("git init --quiet "+quote(remote)).c_str())==0,"git init");req(std::system(("git -C "+quote(remote)+" config user.email strut@example.invalid").c_str())==0,"git email");req(std::system(("git -C "+quote(remote)+" config user.name Strut").c_str())==0,"git name");req(std::system(("git -C "+quote(remote)+" add strut.json main.p").c_str())==0,"git add");req(std::system(("git -C "+quote(remote)+" commit --quiet -m fixture").c_str())==0,"git commit");const auto rev_file=root/"revision";req(std::system(("git -C "+quote(remote)+" rev-parse HEAD > "+quote(rev_file)).c_str())==0,"git revision");std::ifstream rf(rev_file);std::string revision;rf>>revision;
 strut::PackageManifest remote_app;remote_app.name="remote-app";remote_app.version="0.1.0";remote_app.dependencies["remote"]="2.0.0";remote_app.dependency_sources["remote"]={"git",remote.string(),revision};req(strut::write_package_manifest_file(root/"strut.json",remote_app,error),error.c_str());req(strut::write_lockfile(root,remote_app,error),error.c_str());strut::PackageLock remote_lock;req(strut::load_package_lock_file(root/"strut.lock.json",remote_lock,error),error.c_str());req(remote_lock.packages[0].source_kind=="git"&&remote_lock.packages[0].revision==revision,"immutable Git lock");
 const auto locked=read(root/"strut.lock.json");const auto remote_cache=home/"cache/packages/remote/2.0.0"/remote_lock.packages[0].checksum.substr(7);std::filesystem::remove_all(remote_cache);strut::PackageLock installed;req(!strut::install_packages(root,true,false,installed,error)&&error.find("offline")!=std::string::npos,"offline missing cache");req(strut::install_packages(root,false,false,installed,error),error.c_str());req(read(root/"strut.lock.json")==locked,"install preserves lock");req(strut::install_packages(root,true,false,installed,error),error.c_str());
 const auto official_base=root/"official";const auto official_repo=official_base/"sqlite";std::filesystem::create_directories(official_repo);std::ofstream(official_repo/"strut.json")<<R"({"name":"sqlite","version":"1.0.0","entry":"main.p"})";std::ofstream(official_repo/"main.p")<<"function sqlite_fixture() -> int { return 1; }\n";req(std::system(("git init --quiet "+quote(official_repo)).c_str())==0,"official git init");req(std::system(("git -C "+quote(official_repo)+" config user.email strut@example.invalid").c_str())==0,"official git email");req(std::system(("git -C "+quote(official_repo)+" config user.name Strut").c_str())==0,"official git name");req(std::system(("git -C "+quote(official_repo)+" add strut.json main.p").c_str())==0,"official git add");req(std::system(("git -C "+quote(official_repo)+" commit --quiet -m v1").c_str())==0,"official git commit");req(std::system(("git -C "+quote(official_repo)+" tag v1.0.0").c_str())==0,"official git tag");std::ofstream(official_repo/"strut.json")<<R"({"name":"sqlite","version":"1.2.0","entry":"main.p"})";req(std::system(("git -C "+quote(official_repo)+" add strut.json").c_str())==0,"official git add v1.2");req(std::system(("git -C "+quote(official_repo)+" commit --quiet -m v1.2").c_str())==0,"official git commit v1.2");req(std::system(("git -C "+quote(official_repo)+" tag v1.2.0").c_str())==0,"official git tag v1.2");
#ifdef _WIN32
 _putenv_s("STRUT_OFFICIAL_PACKAGE_BASE",official_base.string().c_str());
#else
 setenv("STRUT_OFFICIAL_PACKAGE_BASE",official_base.string().c_str(),1);
#endif
 strut::PackageSource official_source;std::string official_version;req(strut::resolve_official_package_source("sqlite","^1.0.0",official_source,official_version,error),error.c_str());req(official_version=="1.2.0"&&official_source.kind=="official"&&std::filesystem::path(official_source.url).lexically_normal()==official_repo.lexically_normal(),"official highest compatible tag");strut::PackageManifest official_app;official_app.name="official-app";official_app.version="0.1.0";official_app.dependencies["sqlite"]="^1.0.0";official_app.dependency_sources["sqlite"]=official_source;req(strut::write_package_manifest_file(root/"official.json",official_app,error),error.c_str());req(read(root/"official.json").find("\"git\"")==std::string::npos,"official manifest keeps shorthand");req(strut::write_lockfile(root,official_app,error),error.c_str());strut::PackageLock official_lock;req(strut::load_package_lock_file(root/"strut.lock.json",official_lock,error),error.c_str());req(official_lock.packages.size()==1&&official_lock.packages[0].source_kind=="official"&&std::filesystem::path(official_lock.packages[0].source).lexically_normal()==official_repo.lexically_normal(),"official canonical lock identity");req(!strut::resolve_official_package_source("missing","*",official_source,official_version,error)&&error.find("missing")!=std::string::npos,"official missing package diagnostic");
 std::filesystem::create_directories(home/"cache/packages/broken/1.0.0");std::ofstream(home/"cache/packages/broken/1.0.0/strut.json")<<R"({"name":"other","version":"1.0.0"})";strut::PackageManifest broken;broken.name="project";broken.version="0.1.0";broken.dependencies["broken"]="1.0.0";req(!strut::write_lockfile(root,broken,error),"broken cache rejected");
 strut::PackageManifest traversal;traversal.name="project";traversal.version="0.1.0";traversal.dependencies["../escape"]="1.0.0";req(!strut::write_lockfile(root,traversal,error)&&error.find("package name")!=std::string::npos,"programmatic dependency traversal rejected");
 const auto symlink_package=root/"symlink-package";std::filesystem::create_directories(symlink_package);std::ofstream(symlink_package/"strut.json")<<R"({"name":"symlinked","version":"1.0.0"})";std::error_code symlink_error;std::filesystem::create_symlink(root/"outside",symlink_package/"escape",symlink_error);if(!symlink_error){std::filesystem::path ignored;strut::PackageManifest ignored_manifest;req(!strut::cache_local_package(symlink_package,ignored,ignored_manifest,error)&&error.find("symbolic link")!=std::string::npos,"symlink escape rejected");}
 return 0;
}
