#include <cstdlib>
#include <iostream>
#include <string>
#include "strut/lexer.h"
#include "strut/parser.h"
#include "strut/source.h"
namespace {void require(bool c,const char*m){if(!c){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);}} strut::ParseResult parse(std::string t){strut::SourceFile s("fixture.p",std::move(t));strut::Lexer l(s);auto x=l.lex();require(x.ok(),"fixture lex");strut::Parser p(x.tokens);return p.parse();}}
namespace { struct IncrementOperatorParserTests { IncrementOperatorParserTests(){
    auto prefix=parse("operator ++(Counter& x) -> Counter&;");require(prefix.ok()&&prefix.program.statements[0]->operator_fixity==strut::OperatorFixity::prefix,"prefix increment identity");
    auto postfix=parse("operator ++(Counter& x, postfix) -> Counter;");require(postfix.ok()&&postfix.program.statements[0]->operator_fixity==strut::OperatorFixity::postfix&&postfix.program.statements[0]->parameters.size()==1,"postfix marker is structured, not a parameter");
    require(!parse("operator +(Counter& x, postfix) -> Counter;").ok(),"postfix marker rejected for unsupported operator");
    require(!parse("operator ++(postfix) -> Counter;").ok(),"leading postfix marker rejected");
    require(!parse("operator ++(Counter& x, postfix, postfix) -> Counter;").ok(),"repeated postfix marker rejected");
    require(!parse("operator ++(Counter& x, int dummy) -> Counter;").ok(),"dummy parameter spelling rejected");
} } increment_operator_parser_tests; }
int main(){require(parse("x := 2; int y := 3;").ok(),"decl");require(parse("if (x) { y := 1; } for (v : values) { x := v; }").ok(),"control");require(parse("function add[T](T a, T b) -> T { return a + b; } function main() -> void { return; }").ok(),"functions");
auto l=parse("double_it := (x) => x * 2; max := (T x, T y) => { return x > y; }; fetch := async (url) => url; function<(double, double) -> double> mul := (a, b) => a * b; function[T]<(T, T) -> T> pick := (a, b) => a;");require(l.ok(),"lambdas and function types");require(l.program.statements.size()==5,"five lambdas");require(l.program.statements[1]->value->lambda->generic_parameters[0]=="T","inferred generic lambda");
auto ptrs=parse("function f(int* a, const int* b, int* const c, int& d, int& const e, ptr<int> raw) -> void;");require(ptrs.ok(),"pointer/reference surface syntax");require(ptrs.program.statements[0]->parameters[0].type.name=="ptr<int>","safe pointer canonical type");require(ptrs.program.statements[0]->parameters[1].type.name=="ptr<int>" && ptrs.program.statements[0]->parameters[1].type.is_const,"const safe pointer binding type");require(ptrs.program.statements[0]->parameters[2].type.name=="ptr<const int>","pointer to const canonical type");require(ptrs.program.statements[0]->parameters[3].type.name=="ref<int>","reference canonical type");require(ptrs.program.statements[0]->parameters[4].type.name=="ref<const int>","const reference canonical type");require(ptrs.program.statements[0]->parameters[5].type.name=="raw_ptr<int>","raw pointer canonical type");
auto deep=parse("function deep(int** a, int*** b, int* const* c, int** const d, int*& e, int*& const f) -> void;");require(deep.ok(),"recursive pointer/reference syntax");require(deep.program.statements[0]->parameters[0].type.name=="ptr<ptr<int>>","pointer to pointer");require(deep.program.statements[0]->parameters[1].type.name=="ptr<ptr<ptr<int>>>","triple pointer");require(deep.program.statements[0]->parameters[2].type.name=="ptr<ptr<const int>>","nested pointee const");require(deep.program.statements[0]->parameters[3].type.name=="ptr<const ptr<int>>","outer pointee const");require(deep.program.statements[0]->parameters[4].type.name=="ref<ptr<int>>","reference to pointer");require(deep.program.statements[0]->parameters[5].type.name=="ref<const ptr<int>>","reference to const pointer");
auto bad_ptr_ref=parse("function bad(int&* p) -> void;");require(!bad_ptr_ref.ok(),"pointer to reference rejected");
auto typed_lambda=parse("f := (int& value, int* owner, string[] names) => *value;");require(typed_lambda.ok(),"composite typed lambda parameters");
require(parse("f := (int*** owners, int*& alias, string[][4] grid) => 1;").ok(),"nested pointer/reference/array lambda parameters");
require(parse("f := (map<string,vector<int>> values, Result<int?>? result) => 1;").ok(),"nested generic and nullable lambda parameters");
require(parse("vector<function<(int)->int>> callbacks := [];").ok(),"function type nested in generic");
require(parse("f := (const int* const value, function<(int)->int> callback) => callback(*value);").ok(),"const and function lambda parameters");
require(parse("f := ( int & value , int * owner ) => * value;").ok(),"spaced composite lambda parameters");
require(parse("f := (int value, inferred) => value; g := (inferred, int value) => value;").ok(),"typed and inferred lambda parameter combinations");
require(!parse("f := (int& value int other) => 1;").ok(),"missing comma in typed lambda rejected");
require(!parse("f := (int&) => 1;").ok(),"missing composite lambda parameter name rejected");
require(!parse("f := (map<string,vector<int> value) => 1;").ok(),"unterminated nested generic lambda type rejected");
auto raw_deep=parse("function raw(ptr<ptr<int>> a, ptr<int*> b) -> void;");require(raw_deep.ok(),"nested raw pointer syntax");require(raw_deep.program.statements[0]->parameters[0].type.name=="raw_ptr<raw_ptr<int>>","raw pointer to raw pointer");require(raw_deep.program.statements[0]->parameters[1].type.name=="raw_ptr<ptr<int>>","raw pointer to safe pointer");
auto container_ptrs=parse("function stored(vector<int*> owners, map<string,int&> refs) -> void;");require(container_ptrs.ok(),"pointer and reference types inside containers");require(container_ptrs.program.statements[0]->parameters[0].type.name=="vector<ptr<int>>","container safe pointer canonical type");require(container_ptrs.program.statements[0]->parameters[1].type.name=="map<string,ref<int>>","container reference canonical type");
require(!parse("function bad[t](t x) -> t { return x; }").ok(),"lowercase generic rejected");require(parse("function f() -> void { try { throw Error(\"x\"); } catch (Error err) { print(err); } catch { print(\"other\"); } }").ok(),"try catch");require(parse("operator +(Vec a, Vec b) -> Vec { return a; }").ok(),"operator declaration");require(parse("unsafe { x := raw->name; }").ok(),"raw pointer arrow member syntax");require(parse("extern \"C\" function c_add(int a, int b) -> int;").ok(),"extern C function declaration");auto wrong_loop=parse("for (item in items) { print(item); }");require(!wrong_loop.ok()&&!wrong_loop.diagnostics.empty()&&wrong_loop.diagnostics[0].message.find("use `:` rather than `in`")!=std::string::npos,"range loop in diagnostic");
auto priv_struct=parse("struct Counter { private int value; string label; private function bump() -> void { this.value = this.value + 1; } function current() -> int { return this.value; } }");require(priv_struct.ok(),"private field and method parse");require(priv_struct.program.statements[0]->fields.size()==2&&priv_struct.program.statements[0]->fields[0].is_private&&!priv_struct.program.statements[0]->fields[1].is_private,"private field flag parsed");require(priv_struct.program.statements[0]->body.size()==2&&priv_struct.program.statements[0]->body[0]->is_private&&!priv_struct.program.statements[0]->body[1]->is_private,"private method flag parsed");
auto eff_fn=parse("function apply(function<(int) -> string : ParseError> f, int x) -> string : ParseError { return f(x); }");require(eff_fn.ok(),"function type error clause parse");require(eff_fn.program.statements[0]->parameters[0].type.name=="function<(int)->string : ParseError>","function type error clause captured");require(eff_fn.program.statements[0]->error_types.size()==1&&eff_fn.program.statements[0]->error_types[0].name=="ParseError","function declaration error canonicalized");
auto eff_fn_multi=parse("function f(function<(int) -> string : (ParseError, IOError)> cb) -> void;");require(eff_fn_multi.ok(),"function type multi-error clause parse");require(eff_fn_multi.program.statements[0]->parameters[0].type.name=="function<(int)->string : (ParseError, IOError)>","function type multi-error captured");
auto eff_future=parse("function fetch() -> future<int : HttpError> : ExecError;");require(eff_future.ok(),"future error clause parse");require(eff_future.program.statements[0]->return_type->name=="future<int : HttpError>","future error clause captured");
auto eff_lambda=parse("fn := (int x) : (ParseError, IOError) => 0;");require(eff_lambda.ok(),"lambda error clause parse");require(eff_lambda.program.statements[0]->value->lambda->error_types.size()==2,"lambda error clause captured");
auto eff_lambda1=parse("fn := () : Error => 0;");require(eff_lambda1.ok()&&eff_lambda1.program.statements[0]->value->lambda->error_types.size()==1,"lambda single error clause captured");
require(!parse("function main() -> int { map<string : Error> m; return 0; }").ok(),"map rejects error clause in source");require(!parse("function main() -> int { vector<int : Error> v; return 0; }").ok(),"vector rejects error clause in source");require(!parse("function main() -> int { tuple<int : Error> t; return 0; }").ok(),"tuple rejects error clause in source");require(!parse("function main() -> int { set<string : Error> s; return 0; }").ok(),"set rejects error clause in source");require(!parse("function main() -> int { ptr<int : Error> p; return 0; }").ok(),"ptr rejects error clause in source");require(parse("function main() -> int { future<int : Error> f; return 0; }").ok(),"future permits error clause in source");return 0;}
