#include <algorithm>
#include <cstdlib>
#include <iostream>
#include "strut/runtime_components.h"
namespace { void req(bool value,const char* message){if(!value){std::cerr<<"FAIL: "<<message<<'\n';std::exit(1);}} }
int main(){using namespace strut;using Id=RuntimeComponentId;
auto http=resolve_runtime_components({Id::http_client,Id::http_client});req(http.ok(),"HTTP graph resolves");req(http.contains(Id::core)&&http.contains(Id::strings)&&http.contains(Id::json)&&http.contains(Id::networking),"transitive closure");req(std::count(http.ordered.begin(),http.ordered.end(),Id::http_client)==1,"duplicates removed");auto again=resolve_runtime_components({Id::http_client});req(http.ordered==again.ordered,"ordering deterministic");auto before=[&](Id a,Id b){return std::find(http.ordered.begin(),http.ordered.end(),a)<std::find(http.ordered.begin(),http.ordered.end(),b);};req(before(Id::json,Id::http_client)&&before(Id::networking,Id::http_client),"dependencies precede consumers");auto links=http.link_libraries();req(links.size()==1&&links[0]=="curl","component owns link library");req(!resolve_runtime_components({static_cast<Id>(999)}).ok(),"unknown component rejected");
req(!http.contains(Id::async),"synchronous HTTP does not pull in async");
auto server=resolve_runtime_components({Id::http_server});req(server.ok()&&!server.contains(Id::http_server_tls),"plaintext server omits TLS");auto server_tls=resolve_runtime_components({Id::http_server_tls});req(server_tls.contains(Id::http_server)&&server_tls.contains(Id::http_server_tls),"TLS server includes lifecycle runtime");auto tls_links=server_tls.link_libraries();req(std::find(tls_links.begin(),tls_links.end(),"ssl")!=tls_links.end()&&std::find(tls_links.begin(),tls_links.end(),"crypto")!=tls_links.end(),"TLS component owns OpenSSL libraries");
IRProgram program;auto statement=std::make_unique<IRStmt>();statement->value=std::make_unique<IRExpr>();statement->value->text="http_get_async";program.statements.push_back(std::move(statement));auto async_http=analyze_runtime_components(program);req(async_http.contains(Id::http_client)&&async_http.contains(Id::async),"async HTTP requests both components");
auto bytes=resolve_runtime_components({Id::bytes});req(bytes.contains(Id::bytes)&&bytes.contains(Id::strings)&&bytes.contains(Id::collections),"bytes owns string and contiguous collection dependencies");req(bytes.link_libraries().empty(),"bytes adds no native link library");
IRProgram typed;auto declaration=std::make_unique<IRStmt>();declaration->type_name="map<string,ptr<int>[]>";declaration->type_id=intern_type(declaration->type_name);typed.statements.push_back(std::move(declaration));auto nested=analyze_runtime_components(typed);req(nested.contains(Id::collections)&&nested.contains(Id::safe_pointer),"structured nested types request components");
IRProgram tls_method;auto tls_statement=std::make_unique<IRStmt>();tls_statement->value=std::make_unique<IRExpr>();tls_statement->value->kind=IRExpr::Kind::member;tls_statement->value->text="listen_tls";tls_statement->value->left=std::make_unique<IRExpr>();tls_statement->value->left->type_name="http_server";tls_method.statements.push_back(std::move(tls_statement));req(analyze_runtime_components(tls_method).contains(Id::http_server_tls),"member API requests TLS component from canonical registry");
 std::vector<RuntimeComponent> cycle={{Id::core,"a",{Id::strings},{},{}},{Id::strings,"b",{Id::core},{},{}}};req(!resolve_runtime_component_graph(cycle,{Id::core}).ok(),"cycle rejected");auto high=static_cast<Id>(100),high_dependency=static_cast<Id>(101);std::vector<RuntimeComponent> extended={{high_dependency,"dependency",{},{},{}},{high,"high",{high_dependency},{},{}}};auto scaled=resolve_runtime_component_graph(extended,{high});req(scaled.ok()&&scaled.contains(high)&&scaled.contains(high_dependency),"resolver state scales with graph IDs");auto fallback=resolve_runtime_components({Id::full_fallback});req(fallback.ok()&&fallback.fallback,"fallback represented explicitly");return 0;}
