#include <algorithm>
#include <cstdlib>
#include <iostream>
#include "strut/runtime_components.h"
namespace { void req(bool value,const char* message){if(!value){std::cerr<<"FAIL: "<<message<<'\n';std::exit(1);}} }
int main(){using namespace strut;using Id=RuntimeComponentId;
auto http=resolve_runtime_components({Id::http_client,Id::http_client});req(http.ok(),"HTTP graph resolves");req(http.contains(Id::core)&&http.contains(Id::strings)&&http.contains(Id::json)&&http.contains(Id::networking),"transitive closure");req(std::count(http.ordered.begin(),http.ordered.end(),Id::http_client)==1,"duplicates removed");auto again=resolve_runtime_components({Id::http_client});req(http.ordered==again.ordered,"ordering deterministic");auto before=[&](Id a,Id b){return std::find(http.ordered.begin(),http.ordered.end(),a)<std::find(http.ordered.begin(),http.ordered.end(),b);};req(before(Id::json,Id::http_client)&&before(Id::networking,Id::http_client),"dependencies precede consumers");auto links=http.link_libraries();req(links.size()==1&&links[0]=="curl","component owns link library");req(!resolve_runtime_components({static_cast<Id>(999)}).ok(),"unknown component rejected");
req(!http.contains(Id::async),"synchronous HTTP does not pull in async");
auto streaming_http=resolve_runtime_components({Id::http_client_streaming});req(streaming_http.contains(Id::http_client)&&streaming_http.contains(Id::bytes)&&streaming_http.contains(Id::cancellation),"streaming HTTP composes the P2 client with bytes and cancellation");req(streaming_http.link_libraries()==std::vector<std::string>{"curl"},"streaming HTTP retains one libcurl dependency");
auto server=resolve_runtime_components({Id::http_server});req(server.ok()&&!server.contains(Id::http_server_tls),"plaintext server omits TLS");req(server.contains(Id::cancellation),"HTTP server owns request cancellation state");auto server_tls=resolve_runtime_components({Id::http_server_tls});req(server_tls.contains(Id::http_server)&&server_tls.contains(Id::http_server_tls),"TLS server includes lifecycle runtime");auto tls_links=server_tls.link_libraries();req(std::find(tls_links.begin(),tls_links.end(),"ssl")!=tls_links.end()&&std::find(tls_links.begin(),tls_links.end(),"crypto")!=tls_links.end(),"TLS component owns OpenSSL libraries");
IRProgram program;auto statement=std::make_unique<IRStmt>();statement->value=std::make_unique<IRExpr>();statement->value->kind=IRExpr::Kind::call;statement->value->left=std::make_unique<IRExpr>();statement->value->left->kind=IRExpr::Kind::identifier;statement->value->left->text="http_get_async";program.statements.push_back(std::move(statement));auto async_http=analyze_runtime_components(program);req(async_http.contains(Id::http_client)&&async_http.contains(Id::async),"async HTTP requests both components");
IRProgram ordinary;auto identifier=std::make_unique<IRStmt>();identifier->value=std::make_unique<IRExpr>();identifier->value->text="sha256";ordinary.statements.push_back(std::move(identifier));req(!analyze_runtime_components(ordinary).contains(Id::crypto),"bare builtin spelling does not request crypto");
auto bytes=resolve_runtime_components({Id::bytes});req(bytes.contains(Id::bytes)&&bytes.contains(Id::strings)&&bytes.contains(Id::collections),"bytes owns string and contiguous collection dependencies");req(bytes.link_libraries().empty(),"bytes adds no native link library");
 auto io=resolve_runtime_components({Id::io});req(io.contains(Id::bytes)&&!io.contains(Id::process)&&!io.contains(Id::networking),"stream contracts depend on bytes without process or networking");
 auto encoding=resolve_runtime_components({Id::encoding});req(encoding.contains(Id::encoding)&&encoding.contains(Id::bytes)&&!encoding.contains(Id::openssl_crypto),"encoding depends on bytes without OpenSSL");req(encoding.link_libraries().empty(),"encoding adds no native library");
 auto crypto=resolve_runtime_components({Id::crypto});req(crypto.contains(Id::crypto)&&crypto.contains(Id::bytes)&&crypto.contains(Id::openssl_crypto),"crypto composes bytes and OpenSSL crypto");auto crypto_links=crypto.link_libraries();req(crypto_links.size()==1&&crypto_links[0]=="crypto","crypto links libcrypto without libssl");
 auto crypto_tls=resolve_runtime_components({Id::crypto,Id::http_server_tls});auto crypto_tls_links=crypto_tls.link_libraries();auto ssl_position=std::find(crypto_tls_links.begin(),crypto_tls_links.end(),"ssl"),crypto_position=std::find(crypto_tls_links.begin(),crypto_tls_links.end(),"crypto");req(ssl_position!=crypto_tls_links.end()&&crypto_position!=crypto_tls_links.end()&&ssl_position<crypto_position,"mixed crypto and TLS preserve static OpenSSL link order");
 auto crypto_http_tls=resolve_runtime_components({Id::crypto,Id::http_client,Id::http_server_tls});auto mixed_links=crypto_http_tls.link_libraries();auto curl_position=std::find(mixed_links.begin(),mixed_links.end(),"curl");ssl_position=std::find(mixed_links.begin(),mixed_links.end(),"ssl");crypto_position=std::find(mixed_links.begin(),mixed_links.end(),"crypto");req(curl_position<ssl_position&&ssl_position<crypto_position,"HTTP client, TLS and crypto libraries preserve static dependency order");
 auto cancellation=resolve_runtime_components({Id::cancellation});req(cancellation.contains(Id::core)&&cancellation.contains(Id::cancellation)&&!cancellation.contains(Id::process)&&!cancellation.contains(Id::networking)&&!cancellation.contains(Id::http_client),"cancellation is an independent runtime component");req(cancellation.link_libraries().empty(),"cancellation adds no native link library");
 auto process=resolve_runtime_components({Id::process});req(process.contains(Id::cancellation),"process pipe handles depend on unified cancellation");
 IRProgram cancellation_program;auto cancellation_declaration=std::make_unique<IRStmt>();cancellation_declaration->type_name="cancellation_token";cancellation_declaration->type_id=intern_type("cancellation_token");cancellation_program.statements.push_back(std::move(cancellation_declaration));req(analyze_runtime_components(cancellation_program).contains(Id::cancellation),"cancellation types request their component");
 IRProgram request_program;auto request_declaration=std::make_unique<IRStmt>();request_declaration->type_name="http_request";request_declaration->type_id=intern_type("http_request");request_program.statements.push_back(std::move(request_declaration));req(analyze_runtime_components(request_program).contains(Id::http_server),"HTTP request types request the server component");
 IRProgram cookie_program;auto cookie_declaration=std::make_unique<IRStmt>();cookie_declaration->type_name="http_cookie";cookie_declaration->type_id=intern_type("http_cookie");cookie_program.statements.push_back(std::move(cookie_declaration));req(analyze_runtime_components(cookie_program).contains(Id::http_server),"HTTP helper types request the server component");
 auto file_response=resolve_runtime_components({Id::http_file_response});req(file_response.contains(Id::http_file_response)&&file_response.contains(Id::http_server),"HTTP file responses compose over the server component");
 auto ndjson=resolve_runtime_components({Id::http_ndjson});req(ndjson.contains(Id::http_ndjson)&&ndjson.contains(Id::http_server)&&ndjson.contains(Id::json),"NDJSON responses compose JSON over the server component");
 auto websocket=resolve_runtime_components({Id::http_websocket});req(websocket.contains(Id::http_websocket)&&websocket.contains(Id::http_server)&&websocket.contains(Id::bytes)&&!websocket.contains(Id::http_server_tls)&&websocket.link_libraries().empty(),"plaintext WebSocket composes bytes over HTTP without OpenSSL");
IRProgram typed;auto declaration=std::make_unique<IRStmt>();declaration->type_name="map<string,ptr<int>[]>";declaration->type_id=intern_type(declaration->type_name);typed.statements.push_back(std::move(declaration));auto nested=analyze_runtime_components(typed);req(nested.contains(Id::collections)&&nested.contains(Id::safe_pointer),"structured nested types request components");
IRProgram tls_method;auto tls_statement=std::make_unique<IRStmt>();tls_statement->value=std::make_unique<IRExpr>();tls_statement->value->kind=IRExpr::Kind::member;tls_statement->value->text="listen_tls";tls_statement->value->left=std::make_unique<IRExpr>();tls_statement->value->left->type_name="http_server";tls_method.statements.push_back(std::move(tls_statement));req(analyze_runtime_components(tls_method).contains(Id::http_server_tls),"member API requests TLS component from canonical registry");
 std::vector<RuntimeComponent> cycle={{Id::core,"a",{Id::strings},{},{}},{Id::strings,"b",{Id::core},{},{}}};req(!resolve_runtime_component_graph(cycle,{Id::core}).ok(),"cycle rejected");auto high=static_cast<Id>(100),high_dependency=static_cast<Id>(101);std::vector<RuntimeComponent> extended={{high_dependency,"dependency",{},{},{}},{high,"high",{high_dependency},{},{}}};auto scaled=resolve_runtime_component_graph(extended,{high});req(scaled.ok()&&scaled.contains(high)&&scaled.contains(high_dependency),"resolver state scales with graph IDs");auto fallback=resolve_runtime_components({Id::full_fallback});req(fallback.ok()&&fallback.fallback,"fallback represented explicitly");return 0;}
