#include <cstdlib>
#include <iostream>
#include "strut/lexer.h"
#include "strut/parser.h"
#include "strut/sema.h"
#include "strut/source.h"
namespace{void req(bool c,const char*m){if(!c){std::cerr<<"FAIL: "<<m<<'\n';std::exit(1);}} strut::SemanticResult sema(std::string t){strut::SourceFile s("x.p",std::move(t));strut::Lexer l(s);auto lx=l.lex();req(lx.ok(),"lex");strut::Parser p(lx.tokens);auto pr=p.parse();req(pr.ok(),"parse");strut::SemanticAnalyzer a;return a.analyze(pr.program);}struct AdvancedGenericTests{AdvancedGenericTests(){req(sema("function id[T](T x) -> T { return x; } function main() -> int { int[] direct := id([]); return 0; }").ok(),"contextual empty literal generic call");req(sema("function nest[T](T[] xs) -> T[] { return xs; } function main() -> int { int[][] values := nest([[1], [2]]); return 0; }").ok(),"nested generic TypeId unification");req(sema("function id[T](T x) -> T { return x; } function main() -> int { int? maybe := id(1); int* owned := id(new(1)); return 0; }").ok(),"nullable and pointer generic results");req(sema("function pick(int x) -> int { return x; } function pick[T](T x) -> T { return x; } function main() -> int { int x := pick(1); return x; }").ok(),"exact overload outranks generic");}} advanced_generic_tests;
struct RegistryApiTests{RegistryApiTests(){
    req(sema("function main() -> void : NetworkError { app := http_server(); map<string,string> assets; app.static(\"/\", assets); app.listen(\"127.0.0.1\", 8080, 1); }").ok(),"registry HTTP optional signatures");
    req(!sema("function main() -> void : NetworkError { app := http_server(); app.listen(\"127.0.0.1\"); }").ok(),"registry method arity checked");
    req(!sema("function main() -> void : NetworkError { app := http_server(); app.listen(\"127.0.0.1\", \"bad\"); }").ok(),"registry method argument type checked");
    req(!sema("function main() -> void { app := http_server(); app.listen(\"127.0.0.1\", 8080); }").ok(),"registry method checked error enforced");
    req(sema("function main() -> void { channel<int> jobs; int? value := jobs.receive(); bool done := jobs.closed(); }").ok(),"registry generic member return types");
    req(!sema("function main() -> void { channel<int> jobs; string? value := jobs.receive(); }").ok(),"registry generic return type checked");
    req(!sema("function main() -> void { worker := thread(() => { return; }); worker.join(); }").ok(),"thread method checked error enforced");
    req(sema("function main() -> void { bytes a := bytes(); bytes b := [0, 1, 255]; b[1] = 254; uint_8 last := b[2]; bytes c := b.slice(1, 3); string text := c.to_string(); bytes d := bytes.from_string(text); print(a.empty()); print(d.length()); }").ok(),"bytes value surface");
    req(!sema("function main() -> void { bytes value := [256]; }").ok(),"byte literal range checked");
    req(!sema("function main() -> void { bytes value := [0]; string text := value; }").ok(),"bytes require explicit string conversion");
    req(!sema("function main() -> void { const bytes value := [0]; value[0] = 1; }").ok(),"const bytes reject indexed mutation");
    req(!sema("function main() -> void { bytes value := [0]; value.slice(0, \"bad\"); }").ok(),"bytes method arguments checked");
    req(sema("function main() -> void : StreamError { ofstream output := ofstream(\"x\", true); output.write_bytes([0, 255]); output.flush(); output.close(); ifstream input := ifstream(\"x\", true); bytes chunk := input.read_bytes(2); bytes rest := input.read_all_bytes(10); bool done := input.eof(); input.close(); }").ok(),"binary file stream contract");
    req(!sema("function main() -> void { ofstream output; output.write_bytes([0]); }").ok(),"binary stream checked error enforced");
    req(sema("function main() -> void : ExecError { string[] args := []; child := process(\"tool\", args); child.in.write_bytes([0, 255]); child.in.flush(); child.in.close(); bytes data := child.out.read_all_bytes(); child.out.close(); }").ok(),"binary process stream adapters");
    req(sema("function main() -> void : ExecError { cancellation_source source; string[] args := []; child := process(\"tool\", args, source.token()); child.out.read_bytes(1); }").ok(),"process accepts a cancellation token");
    req(!sema("function main() -> void : ExecError { string[] args := []; child := process(\"tool\", args, true); }").ok(),"process rejects a non-token cancellation argument");
    req(!sema("function main() -> void : ExecError { child := process(true, [\"arg\"]); }").ok(),"process rejects a non-string program");
    req(!sema("function main() -> void : ExecError { child := process(\"tool\", [1]); }").ok(),"process rejects non-string arguments");
    req(sema("function main() -> void : ExecError { child := process(\"tool\", []); }").ok(),"process contextually types empty arguments");
    req(!sema("function main() -> void : ExecError { child := process(\"tool\"); }").ok(),"process cancellation overload preserves constructor arity checks");
    req(!sema("function main() -> void : StreamError { ifstream input; input.read_bytes(\"bad\"); }").ok(),"binary stream argument types checked");
    req(sema("include <filesystem>; function main() -> void : FilesystemError { write_file(\"empty.bin\", []); }").ok(),"empty bytes infer through filesystem overload");
    req(sema("function main() -> void : CancellationError { cancellation_source source; cancellation_token token := source.token(); cancellation_token copy := token; bool before := copy.cancelled(); source.cancel(); source.cancel(); copy.wait(); token.throw_if_cancelled(); }").ok(),"unified cancellation source and token contract");
    req(!sema("function main() -> void { cancellation_source source; source.token().throw_if_cancelled(); }").ok(),"cancellation checked error enforced");
    req(!sema("function main() -> void { cancellation_token token; token.cancel(); }").ok(),"cancellation token cannot request cancellation");
    req(sema("function handler(http_request request) -> void { cancellation_token token := request.cancellation; bool stopped := token.cancelled(); }").ok(),"HTTP request exposes its cancellation token");
    req(!sema("function handler(http_request request, cancellation_token replacement) -> void { request.cancellation = replacement; }").ok(),"HTTP request cancellation field is read-only");
    req(!sema("function handler(http_request? request, cancellation_token replacement) -> void { request?.cancellation = replacement; }").ok(),"nullable HTTP request cancellation field is read-only");
    req(sema("function inspect(http_request request) -> void : HttpError { string[] tags := request.query_values.values(\"tag\"); string? session := request.cookies.get(\"session\"); values := request.form(1024); text := request.text(); parsed := request.json(1024); }").ok(),"HTTP request application helpers type check");
    req(!sema("function replace(http_request request, http_values values) -> void { request.query_values = values; }").ok(),"lossless query values are read-only");
    req(sema("function response() -> http_server_response : HttpError { cookie := http_cookie(\"session\", \"value\"); cookie.path = \"/\"; cookie.secure = true; cookie.http_only = true; cookie.same_site = \"Strict\"; result := http_redirect(\"/login\", 303); result.cookies = [cookie]; return result; }").ok(),"structured cookies and redirects type check");
    req(sema("function stream(http_response_writer writer, http_cookie cookie) -> void : NetworkError { writer.cookie(cookie); }").ok(),"streaming response cookies require NetworkError");
    req(sema("function serve(http_request request, http_response_writer writer) -> void : (FilesystemError, NetworkError) { http_serve_file(request, writer, \"asset.bin\"); http_serve_file(request, writer, \"asset.txt\", \"text/plain\"); }").ok(),"HTTP file responses type check with optional content type");
    req(!sema("function serve(http_request request, http_response_writer writer) -> void : NetworkError { http_serve_file(request, writer, \"asset.bin\"); }").ok(),"HTTP file responses require FilesystemError");
    req(sema("function emit(http_request request, http_response_writer writer, json value) -> void : (HttpError, NetworkError) { http_write_ndjson(request, writer, value); }").ok(),"NDJSON record helper type checks");
    req(!sema("function emit(http_request request, http_response_writer writer, json value) -> void : NetworkError { http_write_ndjson(request, writer, value); }").ok(),"NDJSON record helper requires HttpError");
}} registry_api_tests;}
int main(){req(sema("x := 1; { x := 2; }").ok(),"nested shadowing allowed");req(!sema("x := 1; x := 2;").ok(),"same-scope duplicate rejected");req(!sema("function f(int x) -> void { x := 2; }").ok(),"parameter duplicate rejected");req(sema("x := 1; function x() -> void;").ok(),"value/function namespaces separate");req(sema("type user_id := uint_64; user_id id := 7;").ok(),"user alias");req(!sema("type A := B; type B := A;").ok(),"alias cycle rejected");req(sema("x := 1; int_64 y := x; double z := x;").ok(),"inference and widening");req(!sema("const x := 1; x = 2;").ok(),"const enforced");req(!sema("x := 1; x = \"bad\";").ok(),"assignment type checked");req(sema("function main() -> void : ExecError { p := process(\"echo\", [\"hi\"]); p.in.close(); line := p.out.read_line(); code := p.wait(); print(line); print(code); }").ok(),"process api types");req(sema("function risky() -> void : Error { throw Error(\"x\"); } function main() -> void { try { risky(); } catch (Error err) { print(err); } }").ok(),"caught checked error");req(sema("struct User { string name; } function main() -> void { p := new(User { name: \"Ada\" }); unsafe { ptr<User> r := ptr(p); print(r->name); } }").ok(),"raw pointer arrow access in unsafe");req(sema("extern \"C\" function c_add(int a, int b) -> int; function main() -> void { unsafe { print(c_add(2,3)); } }").ok(),"extern C call in unsafe");req(!sema("extern \"C\" function c_add(int a, int b) -> int; function main() -> void { print(c_add(2,3)); }").ok(),"extern C call outside unsafe rejected");req(sema("function main() -> int { return 0; }").ok(),"integer main accepted");req(sema("function main(string cmd, string[] args) -> int { print(cmd); print(args.length); return 0; }").ok(),"argument main accepted without vector module");req(!sema("function main() -> int { if (true) { return 0; } }").ok(),"integer main requires all paths to return");req(!sema("function main() -> int { return; }").ok(),"integer main rejects bare return");req(!sema("function main() -> int { return \"bad\"; }").ok(),"integer main checks return type");req(!sema("function main(int x) -> int { return x; }").ok(),"main rejects invalid parameter shape");req(!sema("function id[T](T x) -> T { return x; } function main() -> int { values := id([]); return 0; }").ok(),"empty literal generic diagnostic");req(sema("function id[T](T x) -> T { return x; } function main() -> int { int[] empty := []; values := id(empty); return 0; }").ok(),"typed empty literal generic call");return 0;}
